export default [
  {
    name: `Repose`,
    lvl: `Lv. 8`,
    skill_type: `Spell`,
    cast: `2.5s`,
    recast: `2.5s`,
    cost: `600 MP`,
    skill_range: `30y`,
    aoe_range: `0y`,
    effect: `Afflicts target with Sleep.
Duration: 30s
Cancels auto-attack upon execution.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/b9cc968fa278a9fdf430db2bab82f184b2231903.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 2.5,
    isGCD: true,
  },
  {
    name: `Esuna`,
    lvl: `Lv. 10`,
    skill_type: `Spell`,
    cast: `1s`,
    recast: `2.5s`,
    cost: `400 MP`,
    skill_range: `30y`,
    aoe_range: `0y`,
    effect: `Removes a single detrimental effect from target.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/266728c8ad811dca5441b08235e1b9cc6039b623.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 1.0,
    isGCD: true,
  },
  {
    name: `Swiftcast`,
    lvl: `Lv. 18`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `60s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Next spell is cast immediately.
Duration: 10s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/27d401b3cfbf90c846ffeaa9f661afb4bd77ce98.png`,
    numDuration: 0,
    numRecast: 60.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Lucid Dreaming`,
    lvl: `Lv. 24`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `60s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Gradually restores own MP.
Potency: 50
Duration: 21s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/216113e0eb1f8f253a35e48106da95998abccf4e.png`,
    numDuration: 0,
    numRecast: 60.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Surecast`,
    lvl: `Lv. 44`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `120s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Spells can be cast without interruption.
Additional Effect: Nullifies most knockback and draw-in effects
Duration: 6s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/fc29836224e4b16309f2c0ab239674e25e55988f.png`,
    numDuration: 0,
    numRecast: 120.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Rescue`,
    lvl: `Lv. 48`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `120s`,
    cost: `-`,
    skill_range: `30y`,
    aoe_range: `0y`,
    effect: `Instantly draws target party member to your side. Cannot be used outside of combat or when target is suffering from certain enfeeblements.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/cb7d21e7457034d62614adb2d8d301ba69db1328.png`,
    numDuration: 0,
    numRecast: 120.0,
    numCast: 0.0,
    isGCD: false,
  },
];
