export default [
  {
    name: `Second Wind`,
    lvl: `Lv. 8`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `120s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Instantly restores own HP.
Cure Potency: 500`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/3482b695719777c57b6922a44982a788a4c8fe9d.png`,
    numDuration: 0,
    numRecast: 120.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Leg Sweep`,
    lvl: `Lv. 10`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `40s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Stuns target.
Duration: 3s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/0bda802bfc0719a4b8de27f9c76c6b0a61a9c867.png`,
    numDuration: 0,
    numRecast: 40.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Bloodbath`,
    lvl: `Lv. 12`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `90s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Converts a portion of physical damage dealt into HP.
Duration: 20s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/420f2d55613f275b3f01b960adb0924ef3832ac0.png`,
    numDuration: 0,
    numRecast: 90.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Feint`,
    lvl: `Lv. 22`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `90s`,
    cost: `-`,
    skill_range: `10y`,
    aoe_range: `0y`,
    effect: `Lowers target's strength and dexterity by 10%.
Duration: 10s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/a6ecfb22e365dde4c2ef80bf096e814853b5892f.png`,
    numDuration: 0,
    numRecast: 90.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Arm's Length`,
    lvl: `Lv. 32`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `120s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Creates a barrier nullifying most knockback and draw-in effects.
Duration: 6s
Additional Effect: Slow +20% when barrier is struck
Duration: 15s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/43e0256d5c0a5f31a25f87024470ab06e82a592d.png`,
    numDuration: 0,
    numRecast: 120.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `True North`,
    lvl: `Lv. 50`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `45s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Nullifies all action direction requirements.
Duration: 10s
Maximum Charges: 2`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/774f123315c94b6ea57de7e46932834285a710e4.png`,
    numDuration: 0,
    numRecast: 45.0,
    numCast: 0.0,
    isGCD: false,
  },
];
