export default [
  {
    name: `Addle`,
    lvl: `Lv. 8`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `90s`,
    cost: `-`,
    skill_range: `25y`,
    aoe_range: `0y`,
    effect: `Lowers target's intelligence and mind by 10%.
Duration: 10s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/b45e688d81b5607246600f904aac008364db0d1e.png`,
    numDuration: 0,
    numRecast: 90.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Swiftcast`,
    lvl: `Lv. 18`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `60s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Next spell is cast immediately.
Duration: 10s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/27d401b3cfbf90c846ffeaa9f661afb4bd77ce98.png`,
    numDuration: 0,
    numRecast: 60.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Lucid Dreaming`,
    lvl: `Lv. 24`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `60s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Gradually restores own MP.
Potency: 50
Duration: 21s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/216113e0eb1f8f253a35e48106da95998abccf4e.png`,
    numDuration: 0,
    numRecast: 60.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Surecast`,
    lvl: `Lv. 44`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `120s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Spells can be cast without interruption.
Additional Effect: Nullifies most knockback and draw-in effects
Duration: 6s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/fc29836224e4b16309f2c0ab239674e25e55988f.png`,
    numDuration: 0,
    numRecast: 120.0,
    numCast: 0.0,
    isGCD: false,
  },
];
