export default [
  {
    name: `Leg Graze`,
    lvl: `Lv. 6`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `30s`,
    cost: `-`,
    skill_range: `25y`,
    aoe_range: `0y`,
    effect: `Afflicts target with Heavy +40%.
Duration: 10s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/bb67eba922e3d99de232117fc7ac3185b02ef278.png`,
    numDuration: 0,
    numRecast: 30.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Second Wind`,
    lvl: `Lv. 8`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `120s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Instantly restores own HP.
Cure Potency: 500`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/3482b695719777c57b6922a44982a788a4c8fe9d.png`,
    numDuration: 0,
    numRecast: 120.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Foot Graze`,
    lvl: `Lv. 10`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `30s`,
    cost: `-`,
    skill_range: `25y`,
    aoe_range: `0y`,
    effect: `Binds target.
Duration: 10s
Cancels auto-attack upon execution.
Target unbound if damage taken.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/4b9fa872246d6483d83b9a5b76d915fd87c4d0c0.png`,
    numDuration: 0,
    numRecast: 30.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Peloton`,
    lvl: `Lv. 20`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `5s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `20y`,
    effect: `Increases movement speed of self and nearby party members.
Duration: 30s
Effect ends when enmity is generated. Has no effect in battle.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/3a82c9dfb439778fdbd3c510ba2ece3fb471fbaf.png`,
    numDuration: 0,
    numRecast: 5.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Head Graze`,
    lvl: `Lv. 24`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `30s`,
    cost: `-`,
    skill_range: `25y`,
    aoe_range: `0y`,
    effect: `Interrupts the use of a target's action.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/622272e5f1fb946133399812cbe0e7f92dbbd1ac.png`,
    numDuration: 0,
    numRecast: 30.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Arm's Length`,
    lvl: `Lv. 32`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `120s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Creates a barrier nullifying most knockback and draw-in effects.
Duration: 6s
Additional Effect: Slow +20% when barrier is struck
Duration: 15s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/43e0256d5c0a5f31a25f87024470ab06e82a592d.png`,
    numDuration: 0,
    numRecast: 120.0,
    numCast: 0.0,
    isGCD: false,
  },
];
