export default [
  {
    name: `Rampart`,
    lvl: `Lv. 8`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `90s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Reduces damage taken by 20%.
Duration: 20s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/d7c6d3b4d6c0387dae2d41ef9580f34393f6ae8e.png`,
    numDuration: 0,
    numRecast: 90.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Low Blow`,
    lvl: `Lv. 12`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `25s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Stuns target.
Duration: 5s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/63272d4625f36791ebfd5880829257c296370a67.png`,
    numDuration: 0,
    numRecast: 25.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Provoke`,
    lvl: `Lv. 15`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `30s`,
    cost: `-`,
    skill_range: `25y`,
    aoe_range: `0y`,
    effect: `Gesture threateningly, placing yourself at the top of a target's enmity list while gaining additional enmity.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/6e8aefd0c8fd9a17b9d839e17a83da5baca0d752.png`,
    numDuration: 0,
    numRecast: 30.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Interject`,
    lvl: `Lv. 18`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `30s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Interrupts the use of a target's action.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/db70da9c641b8d26c2bd7af3bada4e1c9de7bee7.png`,
    numDuration: 0,
    numRecast: 30.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Reprisal`,
    lvl: `Lv. 22`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `60s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `5y`,
    effect: `Reduces damage dealt by nearby enemies by 10%.
Duration: 10s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/eacec4bddcf96b77063939dd55fd6b10075c1792.png`,
    numDuration: 0,
    numRecast: 60.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Arm's Length`,
    lvl: `Lv. 32`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `120s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Creates a barrier nullifying most knockback and draw-in effects.
Duration: 6s
Additional Effect: Slow +20% when barrier is struck
Duration: 15s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/43e0256d5c0a5f31a25f87024470ab06e82a592d.png`,
    numDuration: 0,
    numRecast: 120.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Shirk`,
    lvl: `Lv. 48`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `120s`,
    cost: `-`,
    skill_range: `25y`,
    aoe_range: `0y`,
    effect: `Diverts 25% of enmity to target party member.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/72e0792e97a83d1f58605ebe23ce94017588b3bc.png`,
    numDuration: 0,
    numRecast: 120.0,
    numCast: 0.0,
    isGCD: false,
  },
];
