export default [{
name: `Blizzard`,
lvl: `Lv. 1`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals ice damage with a potency of 180.
Additional Effect: Grants Umbral Ice or removes Astral Fire
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/dab74d4a196c546228d67c91db4bde70c32c45df.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Fire`,
lvl: `Lv. 2`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `800 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals fire damage with a potency of 180.
Additional Effect: Grants Astral Fire or removes Umbral Ice
Duration: 15s
Additional Effect: 40% chance next Fire III will cost no MP and have no cast time
Duration: 18s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/0f0b18de207de52d394b2ca8cb990a38e96587e0.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Transpose`,
lvl: `Lv. 4`,
skill_type: `Ability`,
cast: `Instant`,
recast: `5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Swaps Astral Fire with a single Umbral Ice, or Umbral Ice with a single Astral Fire.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/a90104e0060cd285ad272a51a6ca8a3e74bf3a6f.png`,
numDuration: 0,
numRecast: 5.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Thunder`,
lvl: `Lv. 6`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `200 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals lightning damage with a potency of 30.
Additional Effect: Lightning damage over time
Potency: 40
Duration: 18s
Additional Effect: 10% chance after each tick that the next Thunder spell of any grade will add its full damage over time amount to its initial damage, have no cast time, and cost no MP
Duration: 18s
Only one Thunder spell-induced damage over time effect per caster can be inflicted upon a single target.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/db30f0fa05ce4f541f839c5b2c57cfe0e9fb77f8.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Sleep`,
lvl: `Lv. 10`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `800 MP`,
skill_range: `30y`,
aoe_range: `5y`,
effect: `Puts target and all nearby enemies to sleep.
Duration: 30s
Cancels auto-attack upon execution.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/934b5ddb952cb9f4ace82e1b4cbb69cc962e9366.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Blizzard II`,
lvl: `Lv. 12`,
skill_type: `Spell`,
cast: `2s`,
recast: `2.5s`,
cost: `800 MP`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Deals ice damage with a potency of 50 to all nearby enemies.
Additional Effect: Grants Umbral Ice or removes Astral Fire
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c2e90b9a194294e699bec5ea41cfc4c9d581adfe.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.0,
isGCD: true,
},
{
name: `Scathe`,
lvl: `Lv. 15`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `800 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 100.
Additional Effect: 20% chance potency will double`,
img_link: `https://img.finalfantasyxiv.com/lds/d/9b763aecc46c5559bbbccadfe866fe42d56a9597.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Fire II`,
lvl: `Lv. 18`,
skill_type: `Spell`,
cast: `3s`,
recast: `2.5s`,
cost: `1500 MP`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals fire damage with a potency of 80 to target and all enemies nearby it.
Additional Effect: Grants Astral Fire or removes Umbral Ice
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/8876f1b3cf116acf7138253e0193396c75698651.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 3.0,
isGCD: true,
},
{
name: `Thunder II`,
lvl: `Lv. 26`,
skill_type: `Spell`,
cast: `3s`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals lightning damage with a potency of 30 to target and all enemies nearby it.
Additional Effect: Lightning damage over time
Potency: 30
Duration: 12s
Additional Effect: 3% chance after each tick that the next Thunder spell of any grade will add its full damage over time amount to its initial damage, have no cast time, and cost no MP
Duration: 18s
Only one Thunder spell-induced damage over time effect per caster can be inflicted upon a single target.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/67205b06f51ddd0e07f16441e38e90d59840f1b6.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 3.0,
isGCD: true,
},
{
name: `Manaward`,
lvl: `Lv. 30`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Creates a barrier that nullifies damage totaling up to 30% of maximum HP.
Duration: 20s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/75ed92265dc2dcc6fa1e0b8f22a01258799f222d.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Manafont`,
lvl: `Lv. 30`,
skill_type: `Ability`,
cast: `Instant`,
recast: `180s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Restores 30% of maximum MP.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/11e10bc28bfd98c42e972e830c0869e05541ea0e.png`,
numDuration: 0,
numRecast: 180.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Fire III`,
lvl: `Lv. 34`,
skill_type: `Spell`,
cast: `3.5s`,
recast: `2.5s`,
cost: `2000 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals fire damage with a potency of 240.
Additional Effect: Grants Astral Fire III and removes Umbral Ice
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/3ff8dcabba57f6a697d5a86fc7490884b74eddff.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 3.5,
isGCD: true,
},
{
name: `Freeze`,
lvl: `Lv. 35`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `1000 MP`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals ice damage with a potency of 100 to target and all enemies nearby it.
Additional Effect: Grants Umbral Ice III and removes Astral Fire
Duration: 15s
Additional Effect: Grants 1 Umbral Heart
Umbral Heart Bonus: Nullifies Astral Fire's MP cost increase for Fire spells and reduces MP cost for Flare by one-third`,
img_link: `https://img.finalfantasyxiv.com/lds/d/63a90e88f805172b1b47f55375ac9dff1c98f0c6.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Blizzard III`,
lvl: `Lv. 40`,
skill_type: `Spell`,
cast: `3.5s`,
recast: `2.5s`,
cost: `800 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals ice damage with a potency of 240.
Additional Effect: Grants Umbral Ice III and removes Astral Fire
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/d20e33466b7edf85d74d6ee6874072f51fb849c3.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 3.5,
isGCD: true,
},
{
name: `Thunder III`,
lvl: `Lv. 45`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals lightning damage with a potency of 70.
Additional Effect: Lightning damage over time
Potency: 40
Duration: 24s
Additional Effect: 10% chance after each tick that the next Thunder spell of any grade will add its full damage over time amount to its initial damage, have no cast time, and cost no MP
Duration: 18s
Only one Thunder spell-induced damage over time effect per caster can be inflicted upon a single target.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f3db4ae8cfcf7cc95f994921c84501cb7afc9939.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Aetherial Manipulation`,
lvl: `Lv. 50`,
skill_type: `Ability`,
cast: `Instant`,
recast: `10s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Rush to a target party member's side.
Unable to cast if bound.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/7989a0e388c53e84c0d5a97bee858d46e5256245.png`,
numDuration: 0,
numRecast: 10.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Flare`,
lvl: `Lv. 50`,
skill_type: `Spell`,
cast: `4s`,
recast: `2.5s`,
cost: `All MP`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals fire damage to target and all enemies nearby it with a potency of 260 for the first enemy, and 40% less for all remaining enemies.
Additional Effect: Grants Astral Fire III and removes Umbral Ice
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/294fb97f2db0516f62f2f310c86454bcf3f2c6ec.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 4.0,
isGCD: true,
},
{
name: `Ley Lines`,
lvl: `Lv. 52`,
skill_type: `Ability`,
cast: `Instant`,
recast: `90s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `3y`,
effect: `Connects naturally occurring ley lines to create a circle of power which, while standing within it, reduces spell cast time and recast time, and auto-attack delay by 15%.
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/7bf393214cd7d1952a57a0f45e0564e89e8c1aad.png`,
numDuration: 0,
numRecast: 90.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Sharpcast`,
lvl: `Lv. 54`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Ensures the next Scathe, Fire, or Thunder spell cast will, for the first hit, trigger Scathe's additional effect, Firestarter, or Thundercloud respectively.
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/5e460beec4ae3da0900f179b33190a580486f169.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Enochian`,
lvl: `Lv. 56`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Increases magic damage dealt by 15%. Also allows the casting of Blizzard IV, Fire IV, Despair, and Umbral Soul.
Additional Effect: Grants Polyglot if Enochian is maintained for 30s
Maximum Stacks: 2
Can only be executed while under the effect of Astral Fire or Umbral Ice. Effect is canceled if Astral Fire or Umbral Ice ends.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/354a134bd43820797f037cfcf1c2d685f2e6f3f0.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Blizzard IV`,
lvl: `Lv. 58`,
skill_type: `Spell`,
cast: `2.8s`,
recast: `2.5s`,
cost: `800 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals ice damage with a potency of 300.
Additional Effect: Grants 3 Umbral Hearts
Umbral Heart Bonus: Nullifies Astral Fire's MP cost increase for Fire spells and reduces MP cost for Flare by one-third
Can only be executed while under the effects of both Enochian and Umbral Ice.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/1fb7dc45eac94ac34711ca29ddb958f1c9fea190.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.8,
isGCD: true,
},
{
name: `Fire IV`,
lvl: `Lv. 60`,
skill_type: `Spell`,
cast: `2.8s`,
recast: `2.5s`,
cost: `800 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals fire damage with a potency of 300.
Can only be executed while under the effects of both Enochian and Astral Fire.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/139ff2e48d5105d73b7403fcc4c576c3c9ed2623.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.8,
isGCD: true,
},
{
name: `Between the Lines`,
lvl: `Lv. 62`,
skill_type: `Ability`,
cast: `Instant`,
recast: `3s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Move instantly to Ley Lines drawn by you.
Cannot be executed while bound.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/32548642d653569a0fc39ace16eb658ba99155ad.png`,
numDuration: 0,
numRecast: 3.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Thunder IV`,
lvl: `Lv. 64`,
skill_type: `Spell`,
cast: `3s`,
recast: `2.5s`,
cost: `800 MP`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals lightning damage with a potency of 50 to target and all enemies nearby it.
Additional Effect: Lightning damage over time
Potency: 30
Duration: 18s
Additional Effect: 3% chance after each tick that the next Thunder spell of any grade will add its full damage over time amount to its initial damage, have no cast time, and cost no MP
Duration: 18s
Only one Thunder spell-induced damage over time effect per caster can be inflicted upon a single target.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/166932ad5ad149148cb425174b46d4cee4866032.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 3.0,
isGCD: true,
},
{
name: `Triplecast`,
lvl: `Lv. 66`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `The next three spells will require no cast time.
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/40fe4446617ecf0d5630a850d015bd019fe28809.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Foul`,
lvl: `Lv. 70`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals unaspected damage to target and all enemies nearby it with a potency of 650 for the first enemy, and 25% less for all remaining enemies.
Polyglot Cost: 1`,
img_link: `https://img.finalfantasyxiv.com/lds/d/65188384ad87a6f176bd5ebe49c356fbc5f6c677.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Despair`,
lvl: `Lv. 72`,
skill_type: `Spell`,
cast: `3s`,
recast: `2.5s`,
cost: `All MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals fire damage with a potency of 380.
Additional Effect: Grants Astral Fire III
Duration: 15s
Can only be executed while under the effects of both Enochian and Astral Fire.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/90e3aff2beb4f0b8f42a70c9a0fef5d93d0cf3e0.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 3.0,
isGCD: true,
},
{
name: `Umbral Soul`,
lvl: `Lv. 76`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Grants Umbral Ice and 1 Umbral Heart.
Umbral Heart Bonus: Nullifies Astral Fire's MP cost increase for Fire spells and reduces MP cost for Flare by one-third
Can only be executed while under the effects of both Enochian and Umbral Ice.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/013c4bb28efc30045a3fedea4410d7bf26df6bc4.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Xenoglossy`,
lvl: `Lv. 80`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 750.
Polyglot Cost: 1`,
img_link: `https://img.finalfantasyxiv.com/lds/d/cb30ee43b9fb15668bc4ed0889ebebdd94a383ff.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
]