export default [{
name: `Heavy Shot`,
lvl: `Lv. 1`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 180.
Additional Effect: 20% chance of becoming Straight Shot Ready
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/cc9ee188dc611827ab2d3c5050df83c40dcef0eb.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Straight Shot`,
lvl: `Lv. 2`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 200.
Can only be executed when Straight Shot Ready.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/b8b2d76517013438e2f9adf6ce67fa1fa5902088.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Raging Strikes`,
lvl: `Lv. 4`,
skill_type: `Ability`,
cast: `Instant`,
recast: `80s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Increases damage dealt by 10%.
Duration: 20s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/fc971f4b870f21fdbaab4365f20d4f81a1d73889.png`,
numDuration: 0,
numRecast: 80.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Venomous Bite`,
lvl: `Lv. 6`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Additional Effect: Venom
Potency: 30
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/dd75ae64937b35e73162ef183de3bede67b36359.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Bloodletter`,
lvl: `Lv. 12`,
skill_type: `Ability`,
cast: `Instant`,
recast: `15s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 150.
Shares a recast timer with Rain of Death.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f225020afe9aa9994f2e7eeb75ca592c366a1200.png`,
numDuration: 0,
numRecast: 15.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Repelling Shot`,
lvl: `Lv. 15`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `5y`,
aoe_range: `0y`,
effect: `Jump 10 yalms away from current target.
Cannot be executed while bound.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/80f613a7fdc747a92d50c9bc4a8e601d0d896128.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Quick Nock`,
lvl: `Lv. 18`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `12y`,
aoe_range: `12y`,
effect: `Delivers an attack with a potency of 150 to all enemies in a cone before you.
Additional Effect: 30% chance the recast timer for Bloodletter and Rain of Death will be reset`,
img_link: `https://img.finalfantasyxiv.com/lds/d/fd0d903bdd6c53b9bafbdfdb2e472479c6ba31ce.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Windbite`,
lvl: `Lv. 30`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals wind damage with a potency of 60.
Additional Effect: Wind damage over time
Potency: 40
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f490b7c5b42b575bc04cd9985e512fe9660cce16.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Mage's Ballad`,
lvl: `Lv. 30`,
skill_type: `Spell`,
cast: `Instant`,
recast: `80s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 100.
Additional Effect: Grants Mage's Ballad to all party members within 30 yalms, increasing their damage dealt by 1%
Duration: 30s
Additional Effect: 40％ chance to grant Repertoire when damage over time is dealt by Caustic Bite or Stormbite
Repertoire Effect: Resets the recast timer of Bloodletter and Rain of Death
This action does not share a recast timer with any other actions. Furthermore, the recast timer cannot be affected by other actions.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/ff9a44b034d415e3bb4a830d7bf9ae0080573735.png`,
numDuration: 0,
numRecast: 80.0,
numCast: 0.0,
isGCD: true,
},
{
name: `The Warden's Paean`,
lvl: `Lv. 35`,
skill_type: `Ability`,
cast: `Instant`,
recast: `45s`,
cost: `-`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Removes one select detrimental effect from self or target party member. If the target is not enfeebled, a barrier is created nullifying the target's next detrimental effect suffered.
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/931cac8d988a3dc0f982f9af4beb27a29d70adef.png`,
numDuration: 0,
numRecast: 45.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Barrage`,
lvl: `Lv. 38`,
skill_type: `Ability`,
cast: `Instant`,
recast: `80s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Triples the number of strikes for a single-target weaponskill. Additional effects added only once.
Duration: 10s
Additional Effect: Grants Straight Shot Ready
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/ba6d819e62eae3bd32567df65305a74a7ffc7eb3.png`,
numDuration: 0,
numRecast: 80.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Army's Paeon`,
lvl: `Lv. 40`,
skill_type: `Spell`,
cast: `Instant`,
recast: `80s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 100.
Additional Effect: Grants Army's Paeon to all party members within 30 yalms, increasing their direct hit rate by 3%
Duration: 30s
Additional Effect: 40％ chance to grant Repertoire when damage over time is dealt by Caustic Bite or Stormbite
Repertoire Effect: Reduces weaponskill cast time and recast time, spell cast time and recast time, and auto-attack delay by 4%
Can be stacked up to 4 times.
This action does not share a recast timer with any other actions. Furthermore, the recast timer cannot be affected by other actions.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/03a3b372bdea7a3e627e0236d3c70d0cf976f256.png`,
numDuration: 0,
numRecast: 80.0,
numCast: 0.0,
isGCD: true,
},
{
name: `Rain of Death`,
lvl: `Lv. 45`,
skill_type: `Ability`,
cast: `Instant`,
recast: `15s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `8y`,
effect: `Delivers an attack with a potency of 130 to target and all enemies nearby it.
Shares a recast timer with Bloodletter.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/659e718ee155d7443b17188668bc2a3441f535e2.png`,
numDuration: 0,
numRecast: 15.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Battle Voice`,
lvl: `Lv. 50`,
skill_type: `Ability`,
cast: `Instant`,
recast: `180s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `20y`,
effect: `Increases direct hit rate of all nearby party members by 20%.
Duration: 20s
Can only be executed while singing Mage's Ballad, Army's Paeon, or the Wanderer's Minuet.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/8f1e28ab396359b31bd0b516bfb62ca9813d5861.png`,
numDuration: 0,
numRecast: 180.0,
numCast: 0.0,
isGCD: false,
},
{
name: `The Wanderer's Minuet`,
lvl: `Lv. 52`,
skill_type: `Spell`,
cast: `Instant`,
recast: `80s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 100.
Additional Effect: Grants the Wanderer's Minuet to all party members within 30 yalms, increasing their critical hit rate by 2%
Duration: 30s
Additional Effect: 40％ chance to grant Repertoire when damage over time is dealt by Caustic Bite or Stormbite
Repertoire Effect: Allows execution of Pitch Perfect
Can be stacked up to 3 times.
This action does not share a recast timer with any other actions. Furthermore, the recast timer cannot be affected by other actions.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c34adc6ca7078f11cb1e31da0bb1a659530cc7a1.png`,
numDuration: 0,
numRecast: 80.0,
numCast: 0.0,
isGCD: true,
},
{
name: `Pitch Perfect`,
lvl: `Lv. 52`,
skill_type: `Ability`,
cast: `Instant`,
recast: `3s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100 when Repertoire stack is 1, 250 when Repertoire stack is 2, and 450 when Repertoire stack is 3.
Can only be executed when the Wanderer's Minuet is active.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/7cb040e69b34309ad21035c12ed663e47fe78cd8.png`,
numDuration: 0,
numRecast: 3.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Empyreal Arrow`,
lvl: `Lv. 54`,
skill_type: `Ability`,
cast: `Instant`,
recast: `15s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 230.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/6c0a33c02ee53275228e9db65dcd35acb9db2fff.png`,
numDuration: 0,
numRecast: 15.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Iron Jaws`,
lvl: `Lv. 56`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Additional Effect: If the target is suffering from a Caustic Bite or Stormbite effect inflicted by you, the effect timer is reset
Additional Effect: 35% chance of becoming Straight Shot Ready
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/a63fd6ea58e2655a4b466f8f1ffc946cff449298.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Sidewinder`,
lvl: `Lv. 60`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Additional Effect: If the target is suffering from a Caustic Bite or Stormbite effect inflicted by you, Sidewinder potency is increased to 200 for one effect, or 300 for both
Shares a recast timer with Shadowbite.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/184c29faf9928efb78271977cb796a9d753d25b2.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Troubadour`,
lvl: `Lv. 62`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `20y`,
effect: `Reduces damage taken by self and nearby party members by 10%.
Duration: 15s
Effect cannot be stacked with machinist's Tactician or dancer's Shield Samba.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/543846951d9142d05571cd9cb3f66962bc4818de.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Caustic Bite`,
lvl: `Lv. 64`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 150.
Additional Effect: Poison
Potency: 40
Duration: 30s
Additional Effect: 35% chance of becoming Straight Shot Ready
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/3282eb4e0c1a9e0ec6ee4827318cd7708ea2e437.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Stormbite`,
lvl: `Lv. 64`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals wind damage with a potency of 100.
Additional Effect: Wind damage over time
Potency: 50
Duration: 30s
Additional Effect: 35% chance of becoming Straight Shot Ready
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c1f48098e204f10791175e535621863aabad5bce.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Nature's Minne`,
lvl: `Lv. 66`,
skill_type: `Ability`,
cast: `Instant`,
recast: `90s`,
cost: `-`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Increases HP recovery via healing actions for a party member or self by 20%.
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/ce59e32b7f804df78a64af0afded7e514cd48dbd.png`,
numDuration: 0,
numRecast: 90.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Refulgent Arrow`,
lvl: `Lv. 70`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 330.
Can only be executed when Straight Shot Ready.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/85bab0b10e03a7f6185ea9d56ed895f80868162c.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Shadowbite`,
lvl: `Lv. 72`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Delivers an attack with a potency of 100 to target and all enemies nearby it.
Additional Effect: If the target is suffering from a Caustic Bite or Stormbite effect inflicted by you, Shadowbite potency is increased to 160 for one effect, or 220 for both
Shares a recast timer with Sidewinder.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/7697c9f25d6588e140fda28f56cb52ded07d80e0.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Burst Shot`,
lvl: `Lv. 76`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 230.
Additional Effect: 35% chance of becoming Straight Shot Ready
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/0c56e43fb44ce934b484dd639f2aadf0f836c2f7.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Apex Arrow`,
lvl: `Lv. 80`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `25y`,
effect: `Delivers an attack with a potency of 120 to all enemies in a straight line before you.
Soul Voice Gauge Cost: 20
Potency increases up to 600 as Soul Voice Gauge exceeds minimum cost.
Consumes Soul Voice Gauge upon execution.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/8f6bca4dff4509e474774058a8ad6781bcde078a.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
]