export default [{
name: `Hard Slash`,
lvl: `Lv. 1`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 200.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/3b67422b1bd53c93e53e524213c6ca19dd05de7c.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Syphon Strike`,
lvl: `Lv. 2`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Hard Slash
Combo Potency: 300
Combo Bonus: Restores MP`,
img_link: `https://img.finalfantasyxiv.com/lds/d/459b2eb5794f3cd2a9b483158dfe6e474e8e0498.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Unleash`,
lvl: `Lv. 6`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Deals unaspected damage with a potency of 150 to all nearby enemies.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/5f0399c5e788f70820433fef68715ef5b5ce470f.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Grit`,
lvl: `Lv. 10`,
skill_type: `Ability`,
cast: `Instant`,
recast: `10s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Significantly increases enmity generation.
Effect ends upon reuse.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/ec62ae3c9133c3fc745ca6e67f67537534ffe54c.png`,
numDuration: 0,
numRecast: 10.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Unmend`,
lvl: `Lv. 15`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `15y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 150.
Additional Effect: Increased enmity`,
img_link: `https://img.finalfantasyxiv.com/lds/d/1b521d6a61a77f8dacc7aaec4847fb75f9bb0d4f.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Souleater`,
lvl: `Lv. 26`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Syphon Strike
Combo Potency: 400
Combo Bonus: Restores own HP
Cure Potency: 300
Combo Bonus: Increases Blood Gauge by 20`,
img_link: `https://img.finalfantasyxiv.com/lds/d/2eb1a1873f7f28c06fd3e6784e81c9db09c7e928.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Flood of Darkness`,
lvl: `Lv. 30`,
skill_type: `Ability`,
cast: `Instant`,
recast: `2s`,
cost: `3000 MP`,
skill_range: `10y`,
aoe_range: `10y`,
effect: `Deals unaspected damage with a potency of 250 to all enemies in a straight line before you.
Additional Effect: Grants Darkside, increasing damage dealt by 10%
Duration: 30s
Extends Darkside duration by 30s to a maximum of 60s.
Shares a recast timer with Edge of Darkness.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/a812029242515ddf4207b5cb75ea01693a2c1b11.png`,
numDuration: 0,
numRecast: 2.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Blood Weapon`,
lvl: `Lv. 35`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Increases Blood Gauge by 10 and restores MP upon landing weaponskills or spells.
Effect does not stack when hitting multiple targets with a single attack.
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/2f749663be84c17bc9ca66c5de753056cd8e4b1e.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Shadow Wall`,
lvl: `Lv. 38`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Reduces damage taken by 30%.
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/5acdf7d5de014cc4f32aa364292102cb5d56d230.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Edge of Darkness`,
lvl: `Lv. 40`,
skill_type: `Ability`,
cast: `Instant`,
recast: `2s`,
cost: `3000 MP`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 350.
Additional Effect: Grants Darkside, increasing damage dealt by 10%
Duration: 30s
Extends Darkside duration by 30s to a maximum of 60s.
Shares a recast timer with Flood of Darkness.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f53e01fd248f9293d8e8e7bc7770f0e7d8fc539c.png`,
numDuration: 0,
numRecast: 2.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Dark Mind`,
lvl: `Lv. 45`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Reduces magic vulnerability by 20%.
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/1679e78fdf9b78028b414c568d32eb7d721cd137.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Living Dead`,
lvl: `Lv. 50`,
skill_type: `Ability`,
cast: `Instant`,
recast: `300s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Grants the effect of Living Dead. When HP is reduced to 0 while under the effect of Living Dead, instead of becoming KO'd, your status will change to Walking Dead.
Living Dead Duration: 10s
While under the effect of Walking Dead, most attacks will not lower your HP below 1. If, before the Walking Dead timer runs out, HP is 100% restored, the effect will fade. If 100% is not restored, you will be KO'd.
Walking Dead Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/08d31e5a4996714f59c329794bd3630cf1350e11.png`,
numDuration: 0,
numRecast: 300.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Salted Earth`,
lvl: `Lv. 52`,
skill_type: `Ability`,
cast: `Instant`,
recast: `90s`,
cost: `-`,
skill_range: `15y`,
aoe_range: `5y`,
effect: `Creates a patch of salted earth, dealing unaspected damage with a potency of 60 to any enemies who enter.
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/ec971675f188b5072ec0475ffd1be099740867f8.png`,
numDuration: 0,
numRecast: 90.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Plunge`,
lvl: `Lv. 54`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `15y`,
aoe_range: `0y`,
effect: `Delivers a jumping attack with a potency of 200.
Maximum Charges: 2
Cannot be executed while bound.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/25cce09d671723ba2fd9d056d62a8062632ee2e2.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Abyssal Drain`,
lvl: `Lv. 56`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `15y`,
aoe_range: `5y`,
effect: `Deals unaspected damage with a potency of 200 to target and all enemies nearby it.
Additional Effect: Restores own HP
Cure Potency: 200`,
img_link: `https://img.finalfantasyxiv.com/lds/d/a40ba7b4a718df60049e2ab4b511dd00d5874044.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Carve and Spit`,
lvl: `Lv. 60`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers a threefold attack with a potency of 450.
Additional Effect: Restores MP`,
img_link: `https://img.finalfantasyxiv.com/lds/d/2bfd31f27144476cedb17ba50d930b9b201fda69.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Bloodspiller`,
lvl: `Lv. 62`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 600.
Blood Gauge Cost: 50`,
img_link: `https://img.finalfantasyxiv.com/lds/d/7b61eb99c926db551cedc7f84fff2b069b133468.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Quietus`,
lvl: `Lv. 64`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Delivers an attack with a potency of 210 to all nearby enemies.
Blood Gauge Cost: 50`,
img_link: `https://img.finalfantasyxiv.com/lds/d/efbf874ba5dcd8106e8afc8b0702e3056bb89811.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Delirium`,
lvl: `Lv. 68`,
skill_type: `Ability`,
cast: `Instant`,
recast: `90s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Allows the execution of Quietus and Bloodspiller without cost, restoring MP when landing either weaponskill.
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/e82d4ae427bf708834c30e1e3c9e61c5d3faf04a.png`,
numDuration: 0,
numRecast: 90.0,
numCast: 0.0,
isGCD: false,
},
{
name: `The Blackest Night`,
lvl: `Lv. 70`,
skill_type: `Ability`,
cast: `Instant`,
recast: `15s`,
cost: `3000 MP`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Creates a barrier around target that absorbs damage totaling 25% of target's maximum HP.
Duration: 7s
Grants Dark Arts when barrier is completely absorbed.
Dark Arts Effect: Consume Dark Arts instead of MP to execute Edge of Shadow or Flood of Shadow`,
img_link: `https://img.finalfantasyxiv.com/lds/d/229a267d4d9337bebcb9f7e730450d3eefc2ce6d.png`,
numDuration: 0,
numRecast: 15.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Stalwart Soul`,
lvl: `Lv. 72`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Deals unaspected damage with a potency of 100 to all nearby enemies.
Combo Action: Unleash
Combo Potency: 160
Combo Bonus: Restores MP
Combo Bonus: Increases Blood Gauge by 20`,
img_link: `https://img.finalfantasyxiv.com/lds/d/05f82608f52893cf04e98e4e1a0a30b67b7eac5c.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Flood of Shadow`,
lvl: `Lv. 74`,
skill_type: `Ability`,
cast: `Instant`,
recast: `2s`,
cost: `3000 MP`,
skill_range: `10y`,
aoe_range: `10y`,
effect: `Deals unaspected damage with a potency of 300 to all enemies in a straight line before you.
Additional Effect: Grants Darkside, increasing damage dealt by 10%
Duration: 30s
Extends Darkside duration by 30s to a maximum of 60s.
Shares a recast timer with Edge of Shadow.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/faa33151bc314091f2c3acc3e1ef27b59af5455f.png`,
numDuration: 0,
numRecast: 2.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Edge of Shadow`,
lvl: `Lv. 74`,
skill_type: `Ability`,
cast: `Instant`,
recast: `2s`,
cost: `3000 MP`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 500.
Additional Effect: Grants Darkside, increasing damage dealt by 10%
Duration: 30s
Extends Darkside duration by 30s to a maximum of 60s.
Shares a recast timer with Flood of Shadow.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f7603ff6395f583e4139951c2ce6a60a32a13fcd.png`,
numDuration: 0,
numRecast: 2.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Dark Missionary`,
lvl: `Lv. 76`,
skill_type: `Ability`,
cast: `Instant`,
recast: `90s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `15y`,
effect: `Reduces magic damage taken by self and nearby party members by 10%.
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/3a0fcbe41e50c0c0736dd3c28126f3edb465d2af.png`,
numDuration: 0,
numRecast: 90.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Living Shadow`,
lvl: `Lv. 80`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Conjure a simulacrum of your darkside to fight alongside you.
Simulacrum Attack Potency: 300
Duration: 24s
Blood Gauge Cost: 50`,
img_link: `https://img.finalfantasyxiv.com/lds/d/1922cdacda2abc848e93d3233d965b65b7f13939.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
]