export default [
  {
    name: `Keen Edge`,
    lvl: `Lv. 1`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `2.5s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 200.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/1f355424750fa45ecb53a612689721790d58aea3.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `No Mercy`,
    lvl: `Lv. 2`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `60s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Increases damage dealt by 20%.
Duration: 20s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/c9fbda60383094e547f52670e0972f56d17b51d6.png`,
    numDuration: 0,
    numRecast: 60.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Brutal Shell`,
    lvl: `Lv. 4`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `2.5s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 100.
Combo Action: Keen Edge
Combo Potency: 300
Combo Bonus: Restores own HP
Cure Potency: 150
Combo Bonus: Creates a barrier which nullifies damage equaling HP restored
Duration: 10s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/de141cd4688468e9b362e5f2107f2735fc479a9d.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `Camouflage`,
    lvl: `Lv. 6`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `90s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Increases parry rate by 50% while reducing damage taken by 10%.
Duration: 20s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/57a8504ffc4f6433472c27d4190656b20267980e.png`,
    numDuration: 0,
    numRecast: 90.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Demon Slice`,
    lvl: `Lv. 10`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `2.5s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `5y`,
    effect: `Delivers an attack with a potency of 150 to all nearby enemies.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/918c8a96d006cd87a14647f7ba072d6d3bea7b6f.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `Royal Guard`,
    lvl: `Lv. 10`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `10s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Significantly increases enmity generation.
Effect ends upon reuse.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/91cb7d7110c982c6f9f5475744d1e40bccc7ebd4.png`,
    numDuration: 0,
    numRecast: 10.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Lightning Shot`,
    lvl: `Lv. 15`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `2.5s`,
    cost: `-`,
    skill_range: `15y`,
    aoe_range: `0y`,
    effect: `Delivers a ranged attack with a potency of 150.
Additional Effect: Increased enmity`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/a0b47b5160f2ede6618f6275e7317f6940df4766.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `Danger Zone`,
    lvl: `Lv. 18`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `30s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 350.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/044448f022c502543afe90760e645004619f113d.png`,
    numDuration: 0,
    numRecast: 30.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Solid Barrel`,
    lvl: `Lv. 26`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `2.5s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 100.
Combo Action: Brutal Shell
Combo Potency: 400
Combo Bonus: Adds a Cartridge to your Powder Gauge`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/d427b84e7d8f1665296ffe4bafd25f924f4089bb.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `Burst Strike`,
    lvl: `Lv. 30`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `2.5s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 500.
Cartridge Cost: 1`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/d721922c6ffa3120c3a00fd7c7e8e18b0eea4eb8.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `Nebula`,
    lvl: `Lv. 38`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `120s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Reduces damage taken by 30%.
Duration: 15s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/bfe718bae3496dde51395539206dc46f51ab02ea.png`,
    numDuration: 0,
    numRecast: 120.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Demon Slaughter`,
    lvl: `Lv. 40`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `2.5s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `5y`,
    effect: `Delivers an attack with a potency of 100 to all nearby enemies.
Combo Action: Demon Slice
Combo Potency: 250
Combo Bonus: Adds a Cartridge to your Powder Gauge`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/b79ae927ccdaf2ba4cb310f93a613694994e33e8.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `Aurora`,
    lvl: `Lv. 45`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `60s`,
    cost: `-`,
    skill_range: `30y`,
    aoe_range: `0y`,
    effect: `Grants Regen to target.
Cure Potency: 200
Duration: 18s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/5d7b8e2b6136948d9e60a83db32df38ff577ea46.png`,
    numDuration: 0,
    numRecast: 60.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Superbolide`,
    lvl: `Lv. 50`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `360s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Reduces HP to 1 and renders you impervious to most attacks.
Duration: 8s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/c1369dfeeaeff736303bcaa1163b1d0c95cecc5d.png`,
    numDuration: 0,
    numRecast: 360.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Sonic Break`,
    lvl: `Lv. 54`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `60s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 300.
Additional Effect: Damage over time
Potency: 90
Duration: 30s
This weaponskill does not share a recast timer with any other actions.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/e162c476fa681134b30c1e6957d72087a3961be2.png`,
    numDuration: 0,
    numRecast: 60.0,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `Rough Divide`,
    lvl: `Lv. 56`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `30s`,
    cost: `-`,
    skill_range: `15y`,
    aoe_range: `0y`,
    effect: `Delivers a jumping attack with a potency of 200.
Maximum Charges: 2
Cannot be executed while bound.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/09f67f756fd0d74e1657c72fb536244341eaaffc.png`,
    numDuration: 0,
    numRecast: 30.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Gnashing Fang`,
    lvl: `Lv. 60`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `30s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 450.
Additional Effect: Grants Ready to Rip
Duration: 10s
Cartridge Cost: 1
This weaponskill does not share a recast timer with any other actions.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/5116e6863178e6fd211e7f825bcfbc4caed6c4a1.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `Savage Claw`,
    lvl: `Lv. 60`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `2.5s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 550.
Combo Action: Gnashing Fang
Combo Bonus: Grants Ready to Tear
Duration: 10s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/ed1a2a8067f67e45c657a487cc688f2d888f61c2.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `Wicked Talon`,
    lvl: `Lv. 60`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `2.5s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 650.
Combo Action: Savage Claw
Combo Bonus: Grants Ready to Gouge
Duration: 10s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/99a91c4fc5b2b80b96115b121718316023814484.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `Bow Shock`,
    lvl: `Lv. 62`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `60s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `5y`,
    effect: `Delivers an attack with a potency of 200 to all nearby enemies.
Additional Effect: Damage over time
Potency: 90
Duration: 15s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/74c88b963912680fded097b5954f993bcb3c7453.png`,
    numDuration: 0,
    numRecast: 60.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Heart of Light`,
    lvl: `Lv. 64`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `90s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `15y`,
    effect: `Reduces magic damage taken by self and nearby party members by 10%.
Duration: 15s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/f9d9b053fee9cc223e72ec75a6c6a466c01ff1fb.png`,
    numDuration: 0,
    numRecast: 90.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Heart of Stone`,
    lvl: `Lv. 68`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `25s`,
    cost: `-`,
    skill_range: `30y`,
    aoe_range: `0y`,
    effect: `Reduces damage taken by a party member or self by 15%.
Duration: 7s
Additional Effect: When targeting a party member while under the effect of Brutal Shell, that effect is also granted to the target
Duration: 10s`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/4b251caddff7919d29381569392fdcc100ea7ba2.png`,
    numDuration: 0,
    numRecast: 25.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Continuation`,
    lvl: `Lv. 70`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `1s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `0y`,
    effect: `Allows the firing of successive rounds with your gunblade.
Gnashing Fang may be followed by Jugular Rip.
Savage Claw may be followed by Abdomen Tear.
Wicked Talon may be followed by Eye Gouge.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/bdc2808e0aa3ffc1a1600a032f64c39ea8823068.png`,
    numDuration: 0,
    numRecast: 1.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Jugular Rip`,
    lvl: `Lv. 70`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `1s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 260.
Can only be executed when Ready to Rip.
※This action cannot be assigned to a hotbar.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/9fb706a74fd813e47f919ec0f4ed43bb6b1e41a0.png`,
    numDuration: 0,
    numRecast: 1.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Abdomen Tear`,
    lvl: `Lv. 70`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `1s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 280.
Can only be executed when Ready to Tear.
※This action cannot be assigned to a hotbar.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/9de44be86d9ce1e9d49d778843ad9a894f572b52.png`,
    numDuration: 0,
    numRecast: 1.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Eye Gouge`,
    lvl: `Lv. 70`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `1s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 300.
Can only be executed when Ready to Gouge.
※This action cannot be assigned to a hotbar.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/161fecf7bf67db1dbac94061b6c448683ed963f4.png`,
    numDuration: 0,
    numRecast: 1.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Fated Circle`,
    lvl: `Lv. 72`,
    skill_type: `Weaponskill`,
    cast: `Instant`,
    recast: `2.5s`,
    cost: `-`,
    skill_range: `0y`,
    aoe_range: `5y`,
    effect: `Delivers an attack with a potency of 320 to all nearby enemies.
Cartridge Cost: 1`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/4fe6733e7f9d788870db023d27536aa1b28d8878.png`,
    numDuration: 0,
    numRecast: 2.5,
    numCast: 0.0,
    isGCD: true,
  },
  {
    name: `Bloodfest`,
    lvl: `Lv. 76`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `90s`,
    cost: `-`,
    skill_range: `25y`,
    aoe_range: `0y`,
    effect: `Draws aetheric energy from target, adding 2 Cartridges to your Powder Gauge.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/da098211b040996d8879e3380133f20922a1c35f.png`,
    numDuration: 0,
    numRecast: 90.0,
    numCast: 0.0,
    isGCD: false,
  },
  {
    name: `Blasting Zone`,
    lvl: `Lv. 80`,
    skill_type: `Ability`,
    cast: `Instant`,
    recast: `30s`,
    cost: `-`,
    skill_range: `3y`,
    aoe_range: `0y`,
    effect: `Delivers an attack with a potency of 800.`,
    img_link: `https://img.finalfantasyxiv.com/lds/d/265cd47810cf6fbeffdd5cc86d2cedf20e414971.png`,
    numDuration: 0,
    numRecast: 30.0,
    numCast: 0.0,
    isGCD: false,
  },
];
