export default [{
name: `Split Shot`,
lvl: `Lv. 1`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 180.
Additional Effect: Increases Heat Gauge by 5`,
img_link: `https://img.finalfantasyxiv.com/lds/d/3acf994a5e73fbfd68621b65c964eb1f0524a797.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Slug Shot`,
lvl: `Lv. 2`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Split Shot or Heated Split Shot
Combo Potency: 260
Combo Bonus: Increases Heat Gauge by 5`,
img_link: `https://img.finalfantasyxiv.com/lds/d/63b7f12a11ad10ebd1229c52d22bc8940d2a99a4.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Hot Shot`,
lvl: `Lv. 4`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `40s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 300.
Additional Effect: Increases Battery Gauge by 20
This weaponskill does not share a recast timer with any other actions.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/baf9acdb3b1f787f6503d1db9adc6f00512e976e.png`,
numDuration: 0,
numRecast: 40.0,
numCast: 0.0,
isGCD: true,
},
{
name: `Reassemble`,
lvl: `Lv. 10`,
skill_type: `Ability`,
cast: `Instant`,
recast: `55s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Guarantees that next weaponskill is a critical direct hit.
Duration: 5s
This action does not affect damage over time effects.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/6d9589980c2f48696de9add8d062d7332b7c0a40.png`,
numDuration: 0,
numRecast: 55.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Gauss Round`,
lvl: `Lv. 15`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 150.
Maximum Charges: 3`,
img_link: `https://img.finalfantasyxiv.com/lds/d/93ac71fae3163f278b0eb3b73013a9cf74fe0b17.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Spread Shot`,
lvl: `Lv. 18`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `12y`,
aoe_range: `12y`,
effect: `Delivers an attack with a potency of 180 to all enemies in a cone before you.
Additional Effect: Increases Heat Gauge by 5`,
img_link: `https://img.finalfantasyxiv.com/lds/d/210eda8628f47dd202804d9de1e7cf2bedc3aa5a.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Clean Shot`,
lvl: `Lv. 26`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Slug Shot or Heated Slug Shot
Combo Potency: 340
Combo Bonus: Increases Heat Gauge by 5
Combo Bonus: Increases Battery Gauge by 10`,
img_link: `https://img.finalfantasyxiv.com/lds/d/54b2eb33935d0d34b1ce1925e804928cc6a3e1f6.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Hypercharge`,
lvl: `Lv. 30`,
skill_type: `Ability`,
cast: `Instant`,
recast: `10s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Releases the energy building in your firearm, causing it to become Overheated, increasing the potency of single-target weaponskills by 20.
Duration: 8s
Heat Gauge Cost: 50`,
img_link: `https://img.finalfantasyxiv.com/lds/d/e31cee478ba6cd2aaa2f8dfaac2907d99871e516.png`,
numDuration: 0,
numRecast: 10.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Heat Blast`,
lvl: `Lv. 35`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `1.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 220.
Additional Effect: Reduces the recast time of both Gauss Round and Ricochet by 15s
Can only be executed when firearm is Overheated.
Recast timer cannot be affected by status effects or gear attributes.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/529241f91081dbfcde3ef1a4fb7371458fc36767.png`,
numDuration: 0,
numRecast: 1.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Rook Autoturret`,
lvl: `Lv. 40`,
skill_type: `Ability`,
cast: `Instant`,
recast: `6s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Deploys a single-target battle turret which attacks using Volley Fire, dealing damage with a potency of 80.
Battery Gauge Cost: 50
Duration increases as Battery Gauge exceeds required cost at time of deployment, up to a maximum of 15 seconds.
Consumes Battery Gauge upon execution.
Shuts down when time expires or upon execution of Rook Overdrive.
Shares a recast timer with Rook Overdrive.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/81673b6c91cb826a7543f1bc79e0b65a5cc3fa74.png`,
numDuration: 0,
numRecast: 6.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Rook Overdrive`,
lvl: `Lv. 40`,
skill_type: `Ability`,
cast: `Instant`,
recast: `15s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Orders the rook autoturret to use Rook Overload.
Rook Overload Potency: 400
Potency increases as Battery Gauge exceeds required cost at time of deployment.
The rook autoturret shuts down after execution. If this action is not used manually while the rook autoturret is active, it will be triggered automatically immediately before shutting down.
Shares a recast timer with Rook Autoturret.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/651de364d71f16a9e267890543f126354fc342af.png`,
numDuration: 0,
numRecast: 15.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Rook Overload`,
lvl: `Lv. 40`,
skill_type: `Ability`,
cast: `Instant`,
recast: `-`,
cost: `-`,
skill_range: `40y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 400.
Potency increases as Battery Gauge exceeds required cost at time of deployment.
The rook autoturret shuts down after execution. If this action is not used manually while the rook autoturret is active, it will be triggered automatically immediately before shutting down.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/1ac411a05fda948f1bbff8e9d28dcf5580b226f4.png`,
numDuration: 0,
numRecast: 0.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Wildfire`,
lvl: `Lv. 45`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Covers target's body in a slow-burning pitch. Action is changed to Detonator for the duration of the effect.
Deals damage when time expires or upon executing Detonator.
Potency is increased by 200 for each of your own weaponskills you land prior to the end of the effect.
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/2080ca968b805ffb3123cca9a1c732581e8005a8.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Detonator`,
lvl: `Lv. 45`,
skill_type: `Ability`,
cast: `Instant`,
recast: `1s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Ends the effect of Wildfire, dealing damage to the target.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/b2cf0fea10ef0259fb51c046e15c30f9cfd3a382.png`,
numDuration: 0,
numRecast: 1.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Ricochet`,
lvl: `Lv. 50`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals damage to all nearby enemies with a potency of 150 for the first enemy, and 50% less for all remaining enemies.
Maximum Charges: 3`,
img_link: `https://img.finalfantasyxiv.com/lds/d/033829817f11d65d01acd0c80e0c1b1a9b169eaf.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Auto Crossbow`,
lvl: `Lv. 52`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `1.5s`,
cost: `-`,
skill_range: `12y`,
aoe_range: `12y`,
effect: `Delivers an attack with a potency of 180 to all enemies in a cone before you.
Can only be executed when firearm is Overheated.
Recast timer cannot be affected by status effects or gear attributes.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/ef3c30b4bf9bf645137560a32ac89f278b426a0f.png`,
numDuration: 0,
numRecast: 1.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Heated Split Shot`,
lvl: `Lv. 54`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 220.
Additional Effect: Increases Heat Gauge by 5`,
img_link: `https://img.finalfantasyxiv.com/lds/d/9164ffb4e70e7ef30b8e951a1638bbecc69b1109.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Tactician`,
lvl: `Lv. 56`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `20y`,
effect: `Reduces damage taken by self and nearby party members by 10%.
Duration: 15s
Effect cannot be stacked with bard's Troubadour or dancer's Shield Samba.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f9e71836e8bbb052fd22b9962bd63340adb0dfc3.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Drill`,
lvl: `Lv. 58`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `20s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 700.
Shares a recast timer with Bioblaster.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/8dfc4c73b4f4921e1c1c2768fc59923890261dea.png`,
numDuration: 0,
numRecast: 20.0,
numCast: 0.0,
isGCD: true,
},
{
name: `Heated Slug Shot`,
lvl: `Lv. 60`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Heated Split Shot
Combo Potency: 330
Combo Bonus: Increases Heat Gauge by 5`,
img_link: `https://img.finalfantasyxiv.com/lds/d/9abcf0172e2fb153d8d38a1b6dd0dcc3ef3a6a45.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Heated Clean Shot`,
lvl: `Lv. 64`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Heated Slug Shot
Combo Potency: 440
Combo Bonus: Increases Heat Gauge by 5
Combo Bonus: Increases Battery Gauge by 10`,
img_link: `https://img.finalfantasyxiv.com/lds/d/1aaef339107126e0b5764bbe3f986d37746da2f5.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Barrel Stabilizer`,
lvl: `Lv. 66`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Increases Heat Gauge by 50.
Can only be executed while in combat.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/3b039a1e369434d37c49328cc843fce3a13bc9ad.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Flamethrower`,
lvl: `Lv. 70`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `8y`,
effect: `Delivers damage over time to all enemies in a cone before you.
Potency: 100
Duration: 10s
Effect ends upon using another action or moving (including facing a different direction).
Cancels auto-attack upon execution.
Triggers the cooldown of weaponskills upon execution. Cannot be executed during the cooldown of weaponskills.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/bf1cc7b9e4e47e465878881a6069d4eb7d29b435.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Bioblaster`,
lvl: `Lv. 72`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `20s`,
cost: `-`,
skill_range: `12y`,
aoe_range: `12y`,
effect: `Delivers an attack with a potency of 60 to all enemies in a cone before you.
Additional Effect: Damage over time
Potency: 60
Duration: 15s
Shares a recast timer with Drill.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f933af731ffe811c3e6167076cd7e0c3baec2473.png`,
numDuration: 0,
numRecast: 20.0,
numCast: 0.0,
isGCD: true,
},
{
name: `Air Anchor`,
lvl: `Lv. 76`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `40s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 700.
Additional Effect: Increases Battery Gauge by 20
This action does not share a recast timer with any other actions.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c122a54483460f21b2b095e42b5e351badf0ffa5.png`,
numDuration: 0,
numRecast: 40.0,
numCast: 0.0,
isGCD: true,
},
{
name: `Automaton Queen`,
lvl: `Lv. 80`,
skill_type: `Ability`,
cast: `Instant`,
recast: `6s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Deploys an Automaton Queen to fight at your side.
Battery Gauge Cost: 50
Duration increases as Battery Gauge exceeds minimum cost at time of deployment, up to a maximum of 20 seconds.
Consumes Battery Gauge upon execution.
Shuts down when time expires or upon execution of Queen Overdrive.
Shares a recast timer with Queen Overdrive.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/6fd1cfedc8c271ca6b7d29223dfa13cd1356fbb4.png`,
numDuration: 0,
numRecast: 6.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Queen Overdrive`,
lvl: `Lv. 80`,
skill_type: `Ability`,
cast: `Instant`,
recast: `15s`,
cost: `-`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Orders the Automaton Queen to use Pile Bunker.
Pile Bunker Potency: 800
Potency increases as Battery Gauge exceeds required cost at time of deployment.
The Automaton Queen shuts down after execution. If this action is not used manually while the Automaton Queen is active, it will be triggered automatically immediately before shutting down.
Shares a recast timer with Automaton Queen.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/84c4a3d8f15cb6310c918544c013c9ea3851d351.png`,
numDuration: 0,
numRecast: 15.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Arm Punch`,
lvl: `Lv. 80`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `1.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 150.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/223ea4fbf4e517f28da50b0058591a82cebcc105.png`,
numDuration: 0,
numRecast: 1.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Roller Dash`,
lvl: `Lv. 80`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `3s`,
cost: `-`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Rushes target and delivers an attack with a potency of 300.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/cd4c801cf4e6edfc7102eec39d43abf62fbd6011.png`,
numDuration: 0,
numRecast: 3.0,
numCast: 0.0,
isGCD: true,
},
{
name: `Pile Bunker`,
lvl: `Lv. 80`,
skill_type: `Ability`,
cast: `Instant`,
recast: `-`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 800.
Potency increases as Battery Gauge exceeds required cost at time of deployment.
The Automaton Queen shuts down after execution. If this action is not used manually while the Automaton Queen is active, it will be triggered automatically immediately before shutting down.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c5da4d88f2d69b49d35c77d361ab155a9d52ff5e.png`,
numDuration: 0,
numRecast: 0.0,
numCast: 0.0,
isGCD: false,
},
]