export default [{
name: `Fast Blade`,
lvl: `Lv. 1`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 200.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/99bcbdf58eaef1f02ee48837e943af413af53e09.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Fight or Flight`,
lvl: `Lv. 2`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Increases physical damage dealt by 25%.
Duration: 25s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/246ed520398f36f3e548984d0f3f3a110b19681a.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Riot Blade`,
lvl: `Lv. 4`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Fast Blade
Combo Potency: 300
Combo Bonus: Restores MP`,
img_link: `https://img.finalfantasyxiv.com/lds/d/3eebf0af5d2b6edafc936aec6768dab5ef4622d0.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Total Eclipse`,
lvl: `Lv. 6`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Delivers an attack with a potency of 120 to all nearby enemies.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/173813f1c8e89596e5fba2adabf566af087bfaed.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Shield Bash`,
lvl: `Lv. 10`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 110.
Additional Effect: Stun
Duration: 6s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/fba706dc5b30f5fd32ef49b8f2b5d3f7b79fa6a0.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Iron Will`,
lvl: `Lv. 10`,
skill_type: `Ability`,
cast: `Instant`,
recast: `10s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Significantly increases enmity generation.
Effect ends upon reuse.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/ad275f491d8cb2185acc2f3825f86e0806b873e7.png`,
numDuration: 0,
numRecast: 10.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Shield Lob`,
lvl: `Lv. 15`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `15y`,
aoe_range: `0y`,
effect: `Delivers a ranged attack with a potency of 120.
Additional Effect: Increased enmity`,
img_link: `https://img.finalfantasyxiv.com/lds/d/6618d4bbaea4750bb43f54bf5bce38391b819bda.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Rage of Halone`,
lvl: `Lv. 26`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Riot Blade
Combo Potency: 350`,
img_link: `https://img.finalfantasyxiv.com/lds/d/35bfa874d58985f724d14b641afd465c80b14d89.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Spirits Within`,
lvl: `Lv. 30`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Potency increases up to 370 as own HP nears maximum.
Additional Effect: Restores MP`,
img_link: `https://img.finalfantasyxiv.com/lds/d/5ab3ed87766aaf00f6552ce5b26d0adfb9e7ef74.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Sheltron`,
lvl: `Lv. 35`,
skill_type: `Ability`,
cast: `Instant`,
recast: `5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Block incoming attacks.
Duration: 6s
Oath Gauge Cost: 50`,
img_link: `https://img.finalfantasyxiv.com/lds/d/375def73ea8a882f1b3d11893ffff3e3fe542474.png`,
numDuration: 0,
numRecast: 5.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Sentinel`,
lvl: `Lv. 38`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Reduces damage taken by 30%.
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f47b0631e79f6967f54b270aee6a6f01416d4b4a.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Prominence`,
lvl: `Lv. 40`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Delivers an attack with a potency of 100 to all nearby enemies.
Combo Action: Total Eclipse
Combo Potency: 220
Combo Bonus: Restores MP`,
img_link: `https://img.finalfantasyxiv.com/lds/d/5534572098afb1a8eaeabb97ed810c0c6d491715.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Cover`,
lvl: `Lv. 45`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `10y`,
aoe_range: `0y`,
effect: `Take all damage intended for another party member.
Duration: 12s
Oath Gauge Cost: 50
Can only be executed when member is closer than 10 yalms. Does not activate with certain attacks.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/53f2f1b1fdf34d7d8220c4918d602c6b2403d96e.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Circle of Scorn`,
lvl: `Lv. 50`,
skill_type: `Ability`,
cast: `Instant`,
recast: `25s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Delivers an attack with a potency of 120 to all nearby enemies.
Additional Effect: Damage over time
Potency: 35
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/a64013bb1706bcd5454d5ac0fe487ef959ce4445.png`,
numDuration: 0,
numRecast: 25.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Hallowed Ground`,
lvl: `Lv. 50`,
skill_type: `Ability`,
cast: `Instant`,
recast: `420s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Renders you impervious to most attacks.
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/482e606ade455651d397ce52618845b191b061cf.png`,
numDuration: 0,
numRecast: 420.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Goring Blade`,
lvl: `Lv. 54`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Riot Blade
Combo Potency: 390
Combo Bonus: Damage over time
Potency: 85
Duration: 21s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/71f2fa2eb16725ef75c6ec282c6145e7a6dc5f7a.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Divine Veil`,
lvl: `Lv. 56`,
skill_type: `Ability`,
cast: `Instant`,
recast: `90s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Upon HP recovery via healing magic cast by self or a party member, a protective barrier is cast on all party members within a radius of 15 yalms.
Duration: 30s
Barrier Effect: Prevents damage up to 10% of your maximum HP
Duration: 30s
Effect ends upon additional HP recovery via healing magic.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/73047bd48045d16652f996e370a6fd77aa538721.png`,
numDuration: 0,
numRecast: 90.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Clemency`,
lvl: `Lv. 58`,
skill_type: `Spell`,
cast: `1.5s`,
recast: `2.5s`,
cost: `2000 MP`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Restores target's HP.
Cure Potency: 1,200
Additional Effect: Restores to self 50% of HP restored to target if target is a party member`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f59c8be86912a1ae89de6c6ef36df2c9f88117d4.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 1.5,
isGCD: true,
},
{
name: `Royal Authority`,
lvl: `Lv. 60`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Riot Blade
Combo Potency: 550
Combo Bonus: Grants 3 stacks of Sword Oath
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/6858db3c06ec976d81553fcdf8a834f5b1241bd9.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Intervention`,
lvl: `Lv. 62`,
skill_type: `Ability`,
cast: `Instant`,
recast: `10s`,
cost: `-`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Reduces target party member's damage taken by 10%.
Duration: 6s
Additional Effect: Increases damage reduction by another 50% of the effect of Rampart or Sentinel if either are active
Oath Gauge Cost: 50`,
img_link: `https://img.finalfantasyxiv.com/lds/d/b7c1427dae1778a1cc24c7164cf852685db7f2f1.png`,
numDuration: 0,
numRecast: 10.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Holy Spirit`,
lvl: `Lv. 64`,
skill_type: `Spell`,
cast: `1.5s`,
recast: `2.5s`,
cost: `2000 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 350.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/351b9cb20a5fb685072bd2df74be4ed6f36ed9fa.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 1.5,
isGCD: true,
},
{
name: `Requiescat`,
lvl: `Lv. 68`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 150. Potency increases up to 550 as MP nears maximum.
Additional Effect: Increases attack magic and healing magic potency by 50% if current MP is at 80% or higher, and allows spells to be cast immediately
Duration: 12s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/4089beaa0883c3354beb6c3356230ada47bec198.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Passage of Arms`,
lvl: `Lv. 70`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `8y`,
effect: `Increases block rate to 100% and creates a designated area in a cone behind you in which party members will only suffer 85% of all damage inflicted.
Duration: 18s
Effect ends upon using another action or moving (including facing a different direction).
Cancels auto-attack upon execution.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/1ad92767c4c8f0c4f680a89604d9ceb93ec02b5c.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Holy Circle`,
lvl: `Lv. 72`,
skill_type: `Spell`,
cast: `1.5s`,
recast: `2.5s`,
cost: `2000 MP`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Deals unaspected damage with a potency of 250 to all nearby enemies.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/3badbc44e5cd3de4e95e2d8f613a6041f0ff87e9.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 1.5,
isGCD: true,
},
{
name: `Intervene`,
lvl: `Lv. 74`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `15y`,
aoe_range: `0y`,
effect: `Rushes target and delivers an attack with a potency of 200.
Maximum Charges: 2
Cannot be executed while bound.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/7e380131962f761668dba6e3835b58fd705ab622.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Atonement`,
lvl: `Lv. 76`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 550.
Additional Effect: Restores MP
Can only be executed while under the effect of Sword Oath.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c59f597216e3b58d3eadd890b0b79c1fcbfb3dbf.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Confiteor`,
lvl: `Lv. 80`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `2000 MP`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals unaspected damage with a potency of 800 to target and all enemies nearby it.
Can only be executed while under the effect of Requiescat. Effect fades upon execution.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/d3cfddf0508932bc65804aca58eb321aca0b10e5.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
]