export default [{
name: `Riposte`,
lvl: `Lv. 1`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 130.
Action upgraded to Enchanted Riposte if both Black Mana and White Mana are at 30 or more.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/829d12b425c59b8f698ef40f0604c56f327ab49f.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Jolt`,
lvl: `Lv. 2`,
skill_type: `Spell`,
cast: `2s`,
recast: `2.5s`,
cost: `200 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 180.
Additional Effect: Increases both Black Mana and White Mana by 3`,
img_link: `https://img.finalfantasyxiv.com/lds/d/af64f92ff4059bb0a39c3c5b5dfbaf4601486c30.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.0,
isGCD: true,
},
{
name: `Verthunder`,
lvl: `Lv. 4`,
skill_type: `Spell`,
cast: `5s`,
recast: `2.5s`,
cost: `300 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals lightning damage with a potency of 370.
Additional Effect: Increases Black Mana by 11
Additional Effect: 50% chance of becoming Verfire Ready
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/8417dd7ad78e412aeb4bb4bc7bec3a5983d9204e.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 5.0,
isGCD: true,
},
{
name: `Corps-a-corps`,
lvl: `Lv. 6`,
skill_type: `Ability`,
cast: `Instant`,
recast: `40s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Rushes target and delivers an attack with a potency of 130.
Cannot be executed while bound.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f187ff809ac6f59b06b5ae1429805eca3e608f9d.png`,
numDuration: 0,
numRecast: 40.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Veraero`,
lvl: `Lv. 10`,
skill_type: `Spell`,
cast: `5s`,
recast: `2.5s`,
cost: `300 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals wind damage with a potency of 370.
Additional Effect: Increases White Mana by 11
Additional Effect: 50% chance of becoming Verstone Ready
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/2b80dfebd89e71e1ee06959b5c41fe16333e3c8f.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 5.0,
isGCD: true,
},
{
name: `Scatter`,
lvl: `Lv. 15`,
skill_type: `Spell`,
cast: `5s`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals unaspected damage with a potency of 120 to target and all enemies nearby it.
Additional Effect: Increases both Black Mana and White Mana by 3`,
img_link: `https://img.finalfantasyxiv.com/lds/d/8a9b23d296d51375fdf8c315bc04eb7070d75f94.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 5.0,
isGCD: true,
},
{
name: `Verthunder II`,
lvl: `Lv. 18`,
skill_type: `Spell`,
cast: `2s`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals lightning damage with a potency of 120 to target and all enemies nearby it.
Additional Effect: Increases Black Mana by 7`,
img_link: `https://img.finalfantasyxiv.com/lds/d/fa4d9d0366ee21d3fa767ce44c112ac0cbbb1c99.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.0,
isGCD: true,
},
{
name: `Veraero II`,
lvl: `Lv. 22`,
skill_type: `Spell`,
cast: `2s`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals wind damage with a potency of 120 to target and all enemies nearby it.
Additional Effect: Increases White Mana by 7`,
img_link: `https://img.finalfantasyxiv.com/lds/d/bac3cf60eace06667c9db3e0c157ad7a23ade4be.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.0,
isGCD: true,
},
{
name: `Verfire`,
lvl: `Lv. 26`,
skill_type: `Spell`,
cast: `2s`,
recast: `2.5s`,
cost: `200 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals fire damage with a potency of 300.
Additional Effect: Increases Black Mana by 9
Can only be executed while Verfire Ready is active.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/de70a84a62c01d0f0907e3546b6941002b37f6ed.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.0,
isGCD: true,
},
{
name: `Verstone`,
lvl: `Lv. 30`,
skill_type: `Spell`,
cast: `2s`,
recast: `2.5s`,
cost: `200 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals earth damage with a potency of 300.
Additional Effect: Increases White Mana by 9
Can only be executed while Verstone Ready is active.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/10f4db2a7ceb0353ef32a5b1102bc46951f1cd46.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.0,
isGCD: true,
},
{
name: `Zwerchhau`,
lvl: `Lv. 35`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Riposte or Enchanted Riposte
Combo Potency: 150
Action upgraded to Enchanted Zwerchhau if both Black Mana and White Mana are at 25 or more.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c73a8ad9a9f8a831a50ba8291f816515d3ced3fd.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Displacement`,
lvl: `Lv. 40`,
skill_type: `Ability`,
cast: `Instant`,
recast: `35s`,
cost: `-`,
skill_range: `5y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 200.
Additional Effect: 15-yalm backstep
Cannot be executed while bound.
Shares a recast timer with Engagement.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/fc7592758ea8818cd04090bcc03e372c51dd2ff7.png`,
numDuration: 0,
numRecast: 35.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Fleche`,
lvl: `Lv. 45`,
skill_type: `Ability`,
cast: `Instant`,
recast: `25s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 440.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f915a78e0c9258a73b516e938233748650d1d7f2.png`,
numDuration: 0,
numRecast: 25.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Redoublement`,
lvl: `Lv. 50`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Zwerchhau or Enchanted Zwerchhau
Combo Potency: 230
Action upgraded to Enchanted Redoublement if both Black Mana and White Mana are at 25 or more.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/568871e7199eb505fa32a40267f224df38c7a684.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Acceleration`,
lvl: `Lv. 50`,
skill_type: `Ability`,
cast: `Instant`,
recast: `55s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Ensures the next three casts of Verthunder/Verflare or Veraero/Verholy will, for their first hits, trigger Verfire Ready or Verstone Ready respectively.
Duration: 20s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c27d7e9994601afa20393623de4ffef882da6fa9.png`,
numDuration: 0,
numRecast: 55.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Moulinet`,
lvl: `Lv. 52`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `8y`,
aoe_range: `8y`,
effect: `Delivers an attack with a potency of 60 to all enemies in a cone before you.
Action upgraded to Enchanted Moulinet if both Black Mana and White Mana are at 20 or more.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/3a7619854dba7bd0906e0050bc2bcb3e068728ad.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Vercure`,
lvl: `Lv. 54`,
skill_type: `Spell`,
cast: `2s`,
recast: `2.5s`,
cost: `500 MP`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Restores target's HP.
Cure Potency: 350`,
img_link: `https://img.finalfantasyxiv.com/lds/d/0de6e73e35e1cd6674f6a94b00434d56f2839a76.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.0,
isGCD: true,
},
{
name: `Contre Sixte`,
lvl: `Lv. 56`,
skill_type: `Ability`,
cast: `Instant`,
recast: `35s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `6y`,
effect: `Delivers an attack with a potency of 400 to target and all enemies nearby it.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/917638ed1dc6658381c310f974400a26917701f2.png`,
numDuration: 0,
numRecast: 35.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Embolden`,
lvl: `Lv. 58`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `15y`,
effect: `Increases own magic damage dealt by 10% and physical damage dealt by nearby party members by 10%. Both effects are reduced by 20% every 4s.
Duration: 20s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/5598fd12869a823f87dc4577e1dbb5285975abd4.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Manafication`,
lvl: `Lv. 60`,
skill_type: `Ability`,
cast: `Instant`,
recast: `110s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Doubles current Black Mana and White Mana levels.
Additional Effect: Resets Corps-a-corps, Displacement, and Engagement recast timers
Additional Effect: Increases magic damage dealt by 5%
Duration: 10s
All combos are canceled upon execution of Manafication.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/ca5a3d907ee760fee713ae3b59d1a20a21214c59.png`,
numDuration: 0,
numRecast: 110.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Jolt II`,
lvl: `Lv. 62`,
skill_type: `Spell`,
cast: `2s`,
recast: `2.5s`,
cost: `200 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 280.
Additional Effect: Increases both Black Mana and White Mana by 3`,
img_link: `https://img.finalfantasyxiv.com/lds/d/d43542245d68cb38fe547c1983db0c1592082d65.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.0,
isGCD: true,
},
{
name: `Verraise`,
lvl: `Lv. 64`,
skill_type: `Spell`,
cast: `10s`,
recast: `2.5s`,
cost: `2400 MP`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Resurrects target to a weakened state.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/04be9f3cbd33184be51301a126d1e4a578300520.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 10.0,
isGCD: true,
},
{
name: `Impact`,
lvl: `Lv. 66`,
skill_type: `Spell`,
cast: `5s`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals unaspected damage with a potency of 220 to target and all enemies nearby it.
Additional Effect: Increases both Black Mana and White Mana by 3`,
img_link: `https://img.finalfantasyxiv.com/lds/d/599ca71c9bf9ef750d25dfd9fe575c48697f0ff5.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 5.0,
isGCD: true,
},
{
name: `Verflare`,
lvl: `Lv. 68`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals fire damage with a potency of 600.
Combo Action: Enchanted Redoublement
Additional Effect: Increases Black Mana by 21
Additional Effect: 20% chance of becoming Verfire Ready
Duration: 30s
Chance to become Verfire Ready increases to 100% if White Mana is higher than Black Mana at time of execution.
Verthunder is changed to Verflare upon landing Enchanted Redoublement as a combo action.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f6fe795eec0c27ad0bc86c6057bdf1e542181caf.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Verholy`,
lvl: `Lv. 70`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 600.
Combo Action: Enchanted Redoublement
Additional Effect: Increases White Mana by 21
Additional Effect: 20% chance of becoming Verstone Ready
Duration: 30s
Chance to become Verstone Ready increases to 100% if Black Mana is higher than White Mana at time of execution.
Veraero is changed to Verholy upon landing Enchanted Redoublement as a combo action.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/a144dc13ac9106510b015985c38b2b87f279d245.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Engagement`,
lvl: `Lv. 72`,
skill_type: `Ability`,
cast: `Instant`,
recast: `35s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 150.
Shares a recast timer with Displacement.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/5bf60a4c57372d8ecb9ddbaf394300ced3fb8c5f.png`,
numDuration: 0,
numRecast: 35.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Reprise`,
lvl: `Lv. 76`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Action upgraded to Enchanted Reprise if both Black Mana and White Mana are at 5 or more.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/3f434c573492e9abe9c2fdd051520a3ac64c3319.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Scorch`,
lvl: `Lv. 80`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 700.
Combo Action: Verflare or Verholy
Additional Effect: Increases both Black Mana and White Mana by 7
Jolt II is changed to Scorch upon landing Verflare or Verholy as a combo action.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/2ee00081bebc2256176be4cf444628fb253a976b.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Enchanted Riposte`,
lvl: `Lv. 1`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `1.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 210.
Balance Gauge Cost: 30 Black Mana
Balance Gauge Cost: 30 White Mana
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/b4c473da78a314c59a5c9283078e7923998057c9.png`,
numDuration: 0,
numRecast: 1.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Enchanted Zwerchhau`,
lvl: `Lv. 35`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `1.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 100.
Combo Action: Riposte or Enchanted Riposte
Combo Potency: 290
Balance Gauge Cost: 25 Black Mana
Balance Gauge Cost: 25 White Mana
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/a4c8b727e7ecb306ee366844f8e1791da2cdc82d.png`,
numDuration: 0,
numRecast: 1.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Enchanted Redoublement`,
lvl: `Lv. 50`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.2s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 100.
Combo Action: Enchanted Zwerchhau
Combo Potency: 470
Balance Gauge Cost: 25 Black Mana
Balance Gauge Cost: 25 White Mana
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/d6574657b8287628d9e39790b5d10fca7807bf63.png`,
numDuration: 0,
numRecast: 2.2,
numCast: 0.0,
isGCD: true,
},
{
name: `Enchanted Moulinet`,
lvl: `Lv. 52`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `1.5s`,
cost: `-`,
skill_range: `8y`,
aoe_range: `8y`,
effect: `Deals unaspected damage with a potency of 200 to all enemies in a cone before you.
Balance Gauge Cost: 20 Black Mana
Balance Gauge Cost: 20 White Mana
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/f3861652df45098c1182efc1620ff0e9a73287a6.png`,
numDuration: 0,
numRecast: 1.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Enchanted Reprise`,
lvl: `Lv. 76`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.2s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 300.
Balance Gauge Cost: 5 Black Mana
Balance Gauge Cost: 5 White Mana
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/ce837aa4bd32b8889ababdede32e132b1c6ed6a0.png`,
numDuration: 0,
numRecast: 2.2,
numCast: 0.0,
isGCD: true,
},
]