export default [{
name: `Ruin`,
lvl: `Lv. 1`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `200 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 180.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/eb0ec769cf218f138999031fec8e1eeb6c9d3fb3.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Bio`,
lvl: `Lv. 2`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage over time.
Potency: 20
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/93f61adcffc6644730a017347d91805359b52bdb.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Physick`,
lvl: `Lv. 4`,
skill_type: `Spell`,
cast: `1.5s`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Restores target's HP.
Cure Potency: 400`,
img_link: `https://img.finalfantasyxiv.com/lds/d/e51f309947cde0c36f3a0cd815ca01e268928eb6.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 1.5,
isGCD: true,
},
{
name: `Summon`,
lvl: `Lv. 4`,
skill_type: `Ability`,
cast: `Instant`,
recast: `3s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Summons a caster-type pet to fight at your side.
Shares a recast timer with Summon II and Summon III.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/641fab5d664b55d6cfcdfda2b980f1bdc65009cd.png`,
numDuration: 0,
numRecast: 3.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Miasma`,
lvl: `Lv. 6`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `500 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 20.
Additional Effect: Unaspected damage over time
Potency: 20
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c38a7b712bce114a74082ea7bb7e64028df374f9.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Egi Assault`,
lvl: `Lv. 10`,
skill_type: `Spell`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Orders your Egi to use Aerial Slash if Garuda-Egi is summoned, Crimson Cyclone if Ifrit-Egi is summoned, or Earthen Armor if Titan-Egi is summoned.
Maximum Charges: 2
Can only be executed while in combat.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/a853d2841429294e9d62f8b861689c035cd6e7ee.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: true,
},
{
name: `Resurrection`,
lvl: `Lv. 12`,
skill_type: `Spell`,
cast: `8s`,
recast: `2.5s`,
cost: `2400 MP`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Resurrects target to a weakened state.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/9e61ea15caf1f7c0e4b44943dcbee0178e61a9fd.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 8.0,
isGCD: true,
},
{
name: `Summon II`,
lvl: `Lv. 15`,
skill_type: `Ability`,
cast: `Instant`,
recast: `3s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Summons a support-type pet to fight at your side.
Shares a recast timer with Summon and Summon III.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/1e3b3dd8faa0bb4b321057260355f6d41cbb7b0c.png`,
numDuration: 0,
numRecast: 3.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Fester`,
lvl: `Lv. 18`,
skill_type: `Ability`,
cast: `Instant`,
recast: `5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 100.
Additional Effect: If target is suffering from a Bio or Miasma effect inflicted by you, Fester potency is increased to 200 for one effect, or 300 for both
Effect only applies when the original spells were cast by you.
Aetherflow Gauge Cost: 1`,
img_link: `https://img.finalfantasyxiv.com/lds/d/95b219ec99428d104b6d51366c86174a8799ec6d.png`,
numDuration: 0,
numRecast: 5.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Energy Drain`,
lvl: `Lv. 18`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 100.
Additional Effect: Aetherflow II
Shares a recast timer with Energy Siphon.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/92ea9227a8a09c62eb53852e2c26c0d6763a35c2.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Bio II`,
lvl: `Lv. 26`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `600 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage over time.
Potency: 30
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/62a7841d8036ec98074662efb7b311f440e26178.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Bane`,
lvl: `Lv. 30`,
skill_type: `Ability`,
cast: `Instant`,
recast: `10s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `8y`,
effect: `Spreads a target's Bio and Miasma effects to nearby enemies.
Potency is reduced by 60% for all remaining enemies.
Duration: Full duration of original effects
No effect if target is not suffering from Bio or Miasma effects inflicted by you.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/fc5d27be373e60a94e318cfca4b3e560cf3d9d27.png`,
numDuration: 0,
numRecast: 10.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Summon III`,
lvl: `Lv. 30`,
skill_type: `Ability`,
cast: `Instant`,
recast: `3s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Summons an attacker-type pet to fight at your side.
Shares a recast timer with Summon and Summon II.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/44acef04cdfe75fbcb035a6963d1d8e62ef8f446.png`,
numDuration: 0,
numRecast: 3.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Energy Siphon`,
lvl: `Lv. 35`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals unaspected damage with a potency of 40 to target and all enemies nearby it.
Additional Effect: Aetherflow II
Shares a recast timer with Energy Drain.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/bfe100c153d4aa8669f3694bcb6c93e646a46661.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Ruin II`,
lvl: `Lv. 38`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 160.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/d6875ae1008a9e4b2d04562cff42646752e919c5.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Outburst`,
lvl: `Lv. 40`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals unaspected damage with a potency of 90 to target and all enemies nearby it.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/4951f224141aabd62ba09dcafd878bed25f74306.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Egi Assault II`,
lvl: `Lv. 40`,
skill_type: `Spell`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Orders your Egi to use Slipstream if Garuda-Egi is summoned, Flaming Crush if Ifrit-Egi is summoned, or Mountain Buster if Titan-Egi is summoned.
Maximum Charges: 2
Can only be executed while in combat.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/0b17052116dc92f2e23e81488526fca24b8d8bde.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: true,
},
{
name: `Enkindle`,
lvl: `Lv. 50`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Commands pet to use its signature attack.
Can only be executed while in combat.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/1e6ae92b904543711ecd1c3768f5b91867cf71e7.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Painflare`,
lvl: `Lv. 52`,
skill_type: `Ability`,
cast: `Instant`,
recast: `5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals unaspected damage with a potency of 130 to target and all enemies nearby it.
Aetherflow Gauge Cost: 1`,
img_link: `https://img.finalfantasyxiv.com/lds/d/e1fc13d1c180776b5e5ae839eb71bfd3a6cab7f9.png`,
numDuration: 0,
numRecast: 5.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Ruin III`,
lvl: `Lv. 54`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `200 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 200.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/9785a8d4cce6c87b52c889d85aa3431d6dfb287b.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Tri-disaster`,
lvl: `Lv. 56`,
skill_type: `Ability`,
cast: `Instant`,
recast: `50s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 300.
Additional Effect: Afflicts target with Bio III and Miasma III
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/5d4fab973350bf41b8caf0a1999ef6d939de4f55.png`,
numDuration: 0,
numRecast: 50.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Dreadwyrm Trance`,
lvl: `Lv. 58`,
skill_type: `Ability`,
cast: `Instant`,
recast: `55s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Reduces spell casting time by 2.5 seconds.
Duration: 15s
Additional Effect: Resets Tri-disaster recast timer
Additional Effect: Grants 2 units of Dreadwyrm Aether when effect ends
Can only be executed while in combat.
Cannot be executed with maximum units of Dreadwyrm Aether or when Demi-Bahamut is summoned.
Shares a recast timer with Firebird Trance.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/b0350f66f4db99bf95c92e4c901d4bd5431df0c2.png`,
numDuration: 0,
numRecast: 55.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Deathflare`,
lvl: `Lv. 60`,
skill_type: `Ability`,
cast: `Instant`,
recast: `15s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `5y`,
effect: `Deals unaspected damage to target and all enemies nearby it with a potency of 400 for the first enemy, and 50% less for all remaining enemies.
Can only be executed while in Dreadwyrm Trance. Dreadwyrm Trance fades upon execution.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/0b5f272dce54b591c37601242161deabc19bb4f4.png`,
numDuration: 0,
numRecast: 15.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Ruin IV`,
lvl: `Lv. 62`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `200 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 300.
Can only be executed while under the effect of Further Ruin.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/4fa18aed88e0681d01f23a39c361added6906ee5.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Aetherpact`,
lvl: `Lv. 64`,
skill_type: `Ability`,
cast: `Instant`,
recast: `180s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Orders pet to execute Devotion.
Devotion Effect: Increases damage dealt by all party members within a 15-yalm radius by 5%
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/6c48771f2057af511d7d40568f2208563e313755.png`,
numDuration: 0,
numRecast: 180.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Devotion`,
lvl: `Lv. 64`,
skill_type: `Ability`,
cast: `Instant`,
recast: `-`,
cost: `-`,
skill_range: `0y`,
aoe_range: `15y`,
effect: `Increases damage dealt by all party members within a 15-yalm radius by 5%.
Duration: 15s
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/170ae60053181a9b12acca3634f91bfaf0715dda.png`,
numDuration: 0,
numRecast: 0.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Bio III`,
lvl: `Lv. 66`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `600 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage over time.
Potency: 45
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/14f1962918c2802084c0b1d541bd60094eb20df6.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Miasma III`,
lvl: `Lv. 66`,
skill_type: `Spell`,
cast: `2.5s`,
recast: `2.5s`,
cost: `500 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 45.
Additional Effect: Unaspected damage over time
Potency: 45
Duration: 30s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/7e11eb35b1a4b384f85ddad8ec196da4c973e837.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 2.5,
isGCD: true,
},
{
name: `Summon Bahamut`,
lvl: `Lv. 70`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Summons Demi-Bahamut to fight by your side. Each time you cast a spell on an enemy, Demi-Bahamut will execute Wyrmwave on the same target.
Duration: 20s
Dreadwyrm Aether Cost: 2
Cannot summon Demi-Bahamut unless a pet is already summoned. Current pet will leave the battlefield while Demi-Bahamut is present, and return once gone. Cannot use while under the effect of Dreadwyrm Trance.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/9f2f687c0e4a4adddc7645e1677f6d1c2a5a189d.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Wyrmwave`,
lvl: `Lv. 70`,
skill_type: `Spell`,
cast: `Instant`,
recast: `1.5s`,
cost: `-`,
skill_range: `100y`,
aoe_range: `0y`,
effect: `Deals unaspected damage with a potency of 150.
Will only execute while Demi-Bahamut is summoned.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/0bfe1db0cbbd1018d00b85cedce00a1a50694f28.png`,
numDuration: 0,
numRecast: 1.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Enkindle Bahamut`,
lvl: `Lv. 70`,
skill_type: `Ability`,
cast: `Instant`,
recast: `10s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Orders Demi-Bahamut to execute Akh Morn.
Akh Morn Effect: Deals unaspected damage to target and all enemies nearby it with a potency of 650 for the first enemy, and 50% less for all remaining enemies
Shares a recast timer with Enkindle Phoenix.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c9080f492689821c034f7175e56bf6f62337288b.png`,
numDuration: 0,
numRecast: 10.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Akh Morn`,
lvl: `Lv. 70`,
skill_type: `Ability`,
cast: `Instant`,
recast: `-`,
cost: `-`,
skill_range: `100y`,
aoe_range: `5y`,
effect: `Deals unaspected damage to target and all enemies nearby it with a potency of 650 for the first enemy, and 50% less for all remaining enemies.
Can only be executed while Demi-Bahamut is summoned.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/be4f2daebfedf80889fb7c828c487ab9d7c13d78.png`,
numDuration: 0,
numRecast: 0.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Firebird Trance`,
lvl: `Lv. 72`,
skill_type: `Ability`,
cast: `Instant`,
recast: `55s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Reduces spell casting time by 2.5 seconds.
Duration: 20s
Additional Effect: Resets Tri-disaster recast timer
Additional Effect: Changes Ruin III to Fountain of Fire and Outburst to Brand of Purgatory
Can only be executed after summoning Demi-Bahamut.
Dreadwyrm Trance is changed to Firebird Trance upon Demi-Bahamut leaving the battlefield.
Shares a recast timer with Dreadwyrm Trance.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/5fb8eb1438ee79a61f10c73575aa02fc9eb115de.png`,
numDuration: 0,
numRecast: 55.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Fountain of Fire`,
lvl: `Lv. 72`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `400 MP`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Deals fire damage with a potency of 250.
Additional Effect: Grants Hellish Conduit
Duration: 10s
Can only be executed while under the effect of Firebird Trance.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/052f8bb72467a26083193c335de022a233ffe51a.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Brand of Purgatory`,
lvl: `Lv. 72`,
skill_type: `Spell`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `8y`,
effect: `Deals fire damage to target and all enemies nearby it with a potency of 350 for the first enemy, and 50% less for all remaining enemies.
Can only be executed while under the effects of both Firebird Trance and Hellish Conduit.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/9d6938645b90e58d12dc29feb2dbd58213c20f3b.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Enkindle Phoenix`,
lvl: `Lv. 80`,
skill_type: `Ability`,
cast: `Instant`,
recast: `10s`,
cost: `-`,
skill_range: `25y`,
aoe_range: `0y`,
effect: `Orders Demi-Phoenix to execute Revelation.
Revelation Effect: Deals fire damage to target and all enemies nearby it with a potency of 650 for the first enemy, and 50% less for all remaining enemies
Action replaces Enkindle Bahamut while Demi-Phoenix is summoned.
Shares a recast timer with Enkindle Bahamut.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/2addfa9b7c482ee7ae50282d2594b4d91e54e9fc.png`,
numDuration: 0,
numRecast: 10.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Everlasting Flight`,
lvl: `Lv. 80`,
skill_type: `Ability`,
cast: `Instant`,
recast: `-`,
cost: `-`,
skill_range: `0y`,
aoe_range: `15y`,
effect: `Gradually restores own HP and the HP of all nearby party members.
Cure Potency: 100
Duration: 21s
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/fb7f1c241981bc89ed7b2209b1ce24e448bff644.png`,
numDuration: 0,
numRecast: 0.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Scarlet Flame`,
lvl: `Lv. 80`,
skill_type: `Spell`,
cast: `Instant`,
recast: `1.5s`,
cost: `-`,
skill_range: `100y`,
aoe_range: `0y`,
effect: `Deals fire damage with a potency of 150.
Will only execute while Demi-Phoenix is summoned.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/71fb8f2da2e6d9784414e912d0b504cef0cdaffd.png`,
numDuration: 0,
numRecast: 1.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Revelation`,
lvl: `Lv. 80`,
skill_type: `Ability`,
cast: `Instant`,
recast: `-`,
cost: `-`,
skill_range: `100y`,
aoe_range: `5y`,
effect: `Deals fire damage to target and all enemies nearby it with a potency of 650 for the first enemy, and 50% less for all remaining enemies.
Can only be executed while Demi-Phoenix is summoned.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/31213b40f8cfb6422f76dae96bfe383860179c9d.png`,
numDuration: 0,
numRecast: 0.0,
numCast: 0.0,
isGCD: false,
},
]