export default [{
name: `Heavy Swing`,
lvl: `Lv. 1`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 200.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/d0a5551cfee5942be8bea44f964bdd190a13da06.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Maim`,
lvl: `Lv. 4`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Heavy Swing
Combo Potency: 300
Combo Bonus: Increases Beast Gauge by 10`,
img_link: `https://img.finalfantasyxiv.com/lds/d/0c15275345f559a2ee9963b663d53a266d667348.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Berserk`,
lvl: `Lv. 6`,
skill_type: `Ability`,
cast: `Instant`,
recast: `90s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Guarantees that all attacks are critical and direct hits.
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/8966fc759b5c0ba06e911eda8927ac8f53093cd4.png`,
numDuration: 0,
numRecast: 90.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Overpower`,
lvl: `Lv. 10`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `8y`,
aoe_range: `8y`,
effect: `Delivers an attack with a potency of 130 to all enemies in a cone before you.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/bfaff6eeee5bb789d583c51007541fb945c64514.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Defiance`,
lvl: `Lv. 10`,
skill_type: `Ability`,
cast: `Instant`,
recast: `10s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Significantly increases enmity generation.
Effect ends upon reuse.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/bbacdc24795da0afa734301c2729b5fb8ca16f2c.png`,
numDuration: 0,
numRecast: 10.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Tomahawk`,
lvl: `Lv. 15`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `15y`,
aoe_range: `0y`,
effect: `Delivers a ranged attack with a potency of 140.
Additional Effect: Increased enmity`,
img_link: `https://img.finalfantasyxiv.com/lds/d/0b9d8a35c1157e7c5d5e6ec810f9250c66bdbd48.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Storm's Path`,
lvl: `Lv. 26`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Maim
Combo Potency: 380
Combo Bonus: Restores own HP
Cure Potency: 250
Combo Bonus: Increases Beast Gauge by 20`,
img_link: `https://img.finalfantasyxiv.com/lds/d/3f427ffc482ec322de590cc5cdf326d2b30c1a16.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Thrill of Battle`,
lvl: `Lv. 30`,
skill_type: `Ability`,
cast: `Instant`,
recast: `90s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Increases maximum HP by 20% and restores the amount increased.
Additional Effect: Increases HP recovery via healing actions on self by 20%
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/ab16fd43ecb1ac3ae483d861343a4caf62c8c83c.png`,
numDuration: 0,
numRecast: 90.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Inner Beast`,
lvl: `Lv. 35`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 350.
Beast Gauge Cost: 50`,
img_link: `https://img.finalfantasyxiv.com/lds/d/d2f16df8ac0b4b3292e00a80e3a5712c292615f7.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Vengeance`,
lvl: `Lv. 38`,
skill_type: `Ability`,
cast: `Instant`,
recast: `120s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Reduces damage taken by 30% and delivers an attack with a potency of 55 every time you suffer physical damage.
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/302080891189465dc52435adb5dccdd1d992c9c2.png`,
numDuration: 0,
numRecast: 120.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Mythril Tempest`,
lvl: `Lv. 40`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Delivers an attack with a potency of 100 to all nearby enemies.
Combo Action: Overpower
Combo Potency: 200
Combo Bonus: Extends Storm's Eye duration by 10s to a maximum of 30s
Combo Bonus: Increases Beast Gauge by 20`,
img_link: `https://img.finalfantasyxiv.com/lds/d/bd93dd237a59a47156f4f1590c9b9f87ed774374.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Holmgang`,
lvl: `Lv. 42`,
skill_type: `Ability`,
cast: `Instant`,
recast: `240s`,
cost: `-`,
skill_range: `6y`,
aoe_range: `0y`,
effect: `Brace yourself for an enemy onslaught, preventing most attacks from reducing your HP to less than 1.
Duration: 8s
When a target is selected, halts their movement with chains.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/1db8fdfb21d77dd4af7407c85ace72503dedae46.png`,
numDuration: 0,
numRecast: 240.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Steel Cyclone`,
lvl: `Lv. 45`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Delivers an attack with a potency of 220 to all nearby enemies.
Beast Gauge Cost: 50`,
img_link: `https://img.finalfantasyxiv.com/lds/d/291ca5c8c2af0ee0aba515405daaff0db77d05e7.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Storm's Eye`,
lvl: `Lv. 50`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 100.
Combo Action: Maim
Combo Potency: 380
Combo Bonus: Increases damage dealt by 10%
Duration: 30s
Combo Bonus: Increases Beast Gauge by 10`,
img_link: `https://img.finalfantasyxiv.com/lds/d/731f7509cef0002c3abec5f94bee6ba7e42c163d.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Infuriate`,
lvl: `Lv. 50`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Increases Beast Gauge by 50.
Additional Effect: Grants Nascent Chaos
Duration: 30s
Maximum Charges: 2
Can only be executed while in combat.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/de67fe20daffbd18cd27e061741fceafb11165eb.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Fell Cleave`,
lvl: `Lv. 54`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 590.
Beast Gauge Cost: 50
※Action changes to Inner Chaos while under the effect of Nascent Chaos.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/e39d8e6c506d08f2eae7e9b0bda01119da51dcf8.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Raw Intuition`,
lvl: `Lv. 56`,
skill_type: `Ability`,
cast: `Instant`,
recast: `25s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Reduces damage taken by 20%.
Duration: 6s
Shares a recast timer with Nascent Flash.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/5ea4fc6959eff2545a40f5b589333e83f908e795.png`,
numDuration: 0,
numRecast: 25.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Equilibrium`,
lvl: `Lv. 58`,
skill_type: `Ability`,
cast: `Instant`,
recast: `60s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Restores own HP.
Cure Potency: 1,200`,
img_link: `https://img.finalfantasyxiv.com/lds/d/cb1fa2fba536267515691a0c004acf20479e8a06.png`,
numDuration: 0,
numRecast: 60.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Decimate`,
lvl: `Lv. 60`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Delivers an attack to all nearby enemies with a potency of 250.
Beast Gauge Cost: 50
※Action changes to Chaotic Cyclone while under the effect of Nascent Chaos.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/271c6d766097e727276e4b5f768f9280d4d17fc4.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Onslaught`,
lvl: `Lv. 62`,
skill_type: `Ability`,
cast: `Instant`,
recast: `10s`,
cost: `-`,
skill_range: `20y`,
aoe_range: `0y`,
effect: `Rushes target and delivers an attack with a potency of 100.
Beast Gauge Cost: 20
Cannot be executed while bound.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/054bb2f916120fbfddf36a9f882cc6242efed5a2.png`,
numDuration: 0,
numRecast: 10.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Upheaval`,
lvl: `Lv. 64`,
skill_type: `Ability`,
cast: `Instant`,
recast: `30s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers an attack with a potency of 450.
Beast Gauge Cost: 20`,
img_link: `https://img.finalfantasyxiv.com/lds/d/e729ddff16e7ab80503f95ecdc382fafae70c8e2.png`,
numDuration: 0,
numRecast: 30.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Shake It Off`,
lvl: `Lv. 68`,
skill_type: `Ability`,
cast: `Instant`,
recast: `90s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `15y`,
effect: `Creates a barrier around self and all nearby party members that absorbs damage totaling 15% of maximum HP.
Dispels Thrill of Battle, Vengeance, and Raw Intuition, increasing damage absorbed by 2% for each effect removed.
Duration: 15s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/becf96eb30ec940eaa8b843ddbbb735dcaef1509.png`,
numDuration: 0,
numRecast: 90.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Inner Release`,
lvl: `Lv. 70`,
skill_type: `Ability`,
cast: `Instant`,
recast: `90s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `0y`,
effect: `Allows the use of Beast Gauge actions without cost and nullifies Stun, Sleep, Bind, Heavy, and most knockback and draw-in effects.
Additional Effect: Guarantees that all attacks are critical and direct hits
Duration: 10s`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c73c58c67904c21315da29f3f8fa8c97df3babf8.png`,
numDuration: 0,
numRecast: 90.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Chaotic Cyclone`,
lvl: `Lv. 72`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `0y`,
aoe_range: `5y`,
effect: `Delivers a critical direct hit with a potency of 400 to all nearby enemies.
Additional Effect: Reduces the recast time of Infuriate by 5 seconds
Beast Gauge Cost: 50
Can only be executed while under the effect of Nascent Chaos. Effect fades upon execution.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/03c1a3e87d10ccbf4cf6144990413ea8becc4649.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
{
name: `Nascent Flash`,
lvl: `Lv. 76`,
skill_type: `Ability`,
cast: `Instant`,
recast: `25s`,
cost: `-`,
skill_range: `30y`,
aoe_range: `0y`,
effect: `Grants Nascent Flash to self and Nascent Glint to target party member.
Nascent Flash Effect: Absorbs damage dealt as HP
Nascent Glint Effect: Restores HP equaling 50% of that recovered by Nascent Flash while also reducing damage taken by 10%
Duration: 6s
Shares a recast timer with Raw Intuition.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/c0109f27debf59a5853e7f680f120865e4406de6.png`,
numDuration: 0,
numRecast: 25.0,
numCast: 0.0,
isGCD: false,
},
{
name: `Inner Chaos`,
lvl: `Lv. 80`,
skill_type: `Weaponskill`,
cast: `Instant`,
recast: `2.5s`,
cost: `-`,
skill_range: `3y`,
aoe_range: `0y`,
effect: `Delivers a critical direct hit with a potency of 920.
Additional Effect: Reduces the recast time of Infuriate by 5 seconds
Beast Gauge Cost: 50
Can only be executed while under the effect of Nascent Chaos. Effect fades upon execution.
※This action cannot be assigned to a hotbar.`,
img_link: `https://img.finalfantasyxiv.com/lds/d/8e3b8a79306f9b3fa27b455363d5ba7befbbee04.png`,
numDuration: 0,
numRecast: 2.5,
numCast: 0.0,
isGCD: true,
},
]