export default {
  paladin: "pld",
  warrior: "war",
  darkknight: "drk",
  gunbreaker: "gnb",
  monk: "mnk",
  dragoon: "drg",
  ninja: "nin",
  samurai: "sam",
  bard: "brd",
  machinist: "mch",
  dancer: "dnc",
  blackmage: "blm",
  summoner: "smn",
  redmage: "rdm",
  whitemage: "whm",
  scholar: "sch",
  astrologian: "ast",
};
